// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: City_pb.proto

package com.leocool.sgland.protocol;

public final class CityMsg {
  private CityMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityGuardReq);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityPickReq);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityProcedureRemoveReq);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityProcedureFinishReq);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityProcedureAssignReq);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityVisitRemoveReq);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityVisitRecruitReq);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityVisitStayReq);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityProcedureCancelReq);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.pkgGuardReq);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityVisitResp);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityGuardResp);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.cityPickResp);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.pkgGuardResp);
    registry.add(com.leocool.sgland.protocol.CityMsg.SglCityMsg.pkgPickResp);
  }
  public interface CityGuardReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 slot_id = 1;
    /**
     * <code>optional int32 slot_id = 1;</code>
     */
    boolean hasSlotId();
    /**
     * <code>optional int32 slot_id = 1;</code>
     */
    int getSlotId();

    // optional int32 info_id = 2;
    /**
     * <code>optional int32 info_id = 2;</code>
     */
    boolean hasInfoId();
    /**
     * <code>optional int32 info_id = 2;</code>
     */
    int getInfoId();

    // optional bool is_guard = 3;
    /**
     * <code>optional bool is_guard = 3;</code>
     */
    boolean hasIsGuard();
    /**
     * <code>optional bool is_guard = 3;</code>
     */
    boolean getIsGuard();
  }
  /**
   * Protobuf type {@code City_pb.CityGuardReq}
   */
  public static final class CityGuardReq extends
      com.google.protobuf.GeneratedMessage
      implements CityGuardReqOrBuilder {
    // Use CityGuardReq.newBuilder() to construct.
    private CityGuardReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CityGuardReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CityGuardReq defaultInstance;
    public static CityGuardReq getDefaultInstance() {
      return defaultInstance;
    }

    public CityGuardReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CityGuardReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              slotId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              infoId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isGuard_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_CityGuardReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_CityGuardReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leocool.sgland.protocol.CityMsg.CityGuardReq.class, com.leocool.sgland.protocol.CityMsg.CityGuardReq.Builder.class);
    }

    public static com.google.protobuf.Parser<CityGuardReq> PARSER =
        new com.google.protobuf.AbstractParser<CityGuardReq>() {
      public CityGuardReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CityGuardReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CityGuardReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 slot_id = 1;
    public static final int SLOT_ID_FIELD_NUMBER = 1;
    private int slotId_;
    /**
     * <code>optional int32 slot_id = 1;</code>
     */
    public boolean hasSlotId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 slot_id = 1;</code>
     */
    public int getSlotId() {
      return slotId_;
    }

    // optional int32 info_id = 2;
    public static final int INFO_ID_FIELD_NUMBER = 2;
    private int infoId_;
    /**
     * <code>optional int32 info_id = 2;</code>
     */
    public boolean hasInfoId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 info_id = 2;</code>
     */
    public int getInfoId() {
      return infoId_;
    }

    // optional bool is_guard = 3;
    public static final int IS_GUARD_FIELD_NUMBER = 3;
    private boolean isGuard_;
    /**
     * <code>optional bool is_guard = 3;</code>
     */
    public boolean hasIsGuard() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool is_guard = 3;</code>
     */
    public boolean getIsGuard() {
      return isGuard_;
    }

    private void initFields() {
      slotId_ = 0;
      infoId_ = 0;
      isGuard_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, slotId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, infoId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isGuard_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, slotId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, infoId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isGuard_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.leocool.sgland.protocol.CityMsg.CityGuardReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityGuardReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityGuardReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityGuardReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityGuardReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityGuardReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityGuardReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityGuardReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityGuardReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityGuardReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leocool.sgland.protocol.CityMsg.CityGuardReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code City_pb.CityGuardReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leocool.sgland.protocol.CityMsg.CityGuardReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_CityGuardReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_CityGuardReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leocool.sgland.protocol.CityMsg.CityGuardReq.class, com.leocool.sgland.protocol.CityMsg.CityGuardReq.Builder.class);
      }

      // Construct using com.leocool.sgland.protocol.CityMsg.CityGuardReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        slotId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        infoId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        isGuard_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_CityGuardReq_descriptor;
      }

      public com.leocool.sgland.protocol.CityMsg.CityGuardReq getDefaultInstanceForType() {
        return com.leocool.sgland.protocol.CityMsg.CityGuardReq.getDefaultInstance();
      }

      public com.leocool.sgland.protocol.CityMsg.CityGuardReq build() {
        com.leocool.sgland.protocol.CityMsg.CityGuardReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leocool.sgland.protocol.CityMsg.CityGuardReq buildPartial() {
        com.leocool.sgland.protocol.CityMsg.CityGuardReq result = new com.leocool.sgland.protocol.CityMsg.CityGuardReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.slotId_ = slotId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.infoId_ = infoId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isGuard_ = isGuard_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leocool.sgland.protocol.CityMsg.CityGuardReq) {
          return mergeFrom((com.leocool.sgland.protocol.CityMsg.CityGuardReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leocool.sgland.protocol.CityMsg.CityGuardReq other) {
        if (other == com.leocool.sgland.protocol.CityMsg.CityGuardReq.getDefaultInstance()) return this;
        if (other.hasSlotId()) {
          setSlotId(other.getSlotId());
        }
        if (other.hasInfoId()) {
          setInfoId(other.getInfoId());
        }
        if (other.hasIsGuard()) {
          setIsGuard(other.getIsGuard());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leocool.sgland.protocol.CityMsg.CityGuardReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leocool.sgland.protocol.CityMsg.CityGuardReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 slot_id = 1;
      private int slotId_ ;
      /**
       * <code>optional int32 slot_id = 1;</code>
       */
      public boolean hasSlotId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 slot_id = 1;</code>
       */
      public int getSlotId() {
        return slotId_;
      }
      /**
       * <code>optional int32 slot_id = 1;</code>
       */
      public Builder setSlotId(int value) {
        bitField0_ |= 0x00000001;
        slotId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 slot_id = 1;</code>
       */
      public Builder clearSlotId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        slotId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 info_id = 2;
      private int infoId_ ;
      /**
       * <code>optional int32 info_id = 2;</code>
       */
      public boolean hasInfoId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 info_id = 2;</code>
       */
      public int getInfoId() {
        return infoId_;
      }
      /**
       * <code>optional int32 info_id = 2;</code>
       */
      public Builder setInfoId(int value) {
        bitField0_ |= 0x00000002;
        infoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 info_id = 2;</code>
       */
      public Builder clearInfoId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        infoId_ = 0;
        onChanged();
        return this;
      }

      // optional bool is_guard = 3;
      private boolean isGuard_ ;
      /**
       * <code>optional bool is_guard = 3;</code>
       */
      public boolean hasIsGuard() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool is_guard = 3;</code>
       */
      public boolean getIsGuard() {
        return isGuard_;
      }
      /**
       * <code>optional bool is_guard = 3;</code>
       */
      public Builder setIsGuard(boolean value) {
        bitField0_ |= 0x00000004;
        isGuard_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_guard = 3;</code>
       */
      public Builder clearIsGuard() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isGuard_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:City_pb.CityGuardReq)
    }

    static {
      defaultInstance = new CityGuardReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:City_pb.CityGuardReq)
  }

  public interface CityProcedureAssignReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    // repeated int32 hero_id = 2;
    /**
     * <code>repeated int32 hero_id = 2;</code>
     */
    java.util.List<java.lang.Integer> getHeroIdList();
    /**
     * <code>repeated int32 hero_id = 2;</code>
     */
    int getHeroIdCount();
    /**
     * <code>repeated int32 hero_id = 2;</code>
     */
    int getHeroId(int index);
  }
  /**
   * Protobuf type {@code City_pb.CityProcedureAssignReq}
   */
  public static final class CityProcedureAssignReq extends
      com.google.protobuf.GeneratedMessage
      implements CityProcedureAssignReqOrBuilder {
    // Use CityProcedureAssignReq.newBuilder() to construct.
    private CityProcedureAssignReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CityProcedureAssignReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CityProcedureAssignReq defaultInstance;
    public static CityProcedureAssignReq getDefaultInstance() {
      return defaultInstance;
    }

    public CityProcedureAssignReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CityProcedureAssignReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                heroId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              heroId_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                heroId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                heroId_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          heroId_ = java.util.Collections.unmodifiableList(heroId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_CityProcedureAssignReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_CityProcedureAssignReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq.class, com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq.Builder.class);
    }

    public static com.google.protobuf.Parser<CityProcedureAssignReq> PARSER =
        new com.google.protobuf.AbstractParser<CityProcedureAssignReq>() {
      public CityProcedureAssignReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CityProcedureAssignReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CityProcedureAssignReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // repeated int32 hero_id = 2;
    public static final int HERO_ID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> heroId_;
    /**
     * <code>repeated int32 hero_id = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getHeroIdList() {
      return heroId_;
    }
    /**
     * <code>repeated int32 hero_id = 2;</code>
     */
    public int getHeroIdCount() {
      return heroId_.size();
    }
    /**
     * <code>repeated int32 hero_id = 2;</code>
     */
    public int getHeroId(int index) {
      return heroId_.get(index);
    }

    private void initFields() {
      id_ = 0;
      heroId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < heroId_.size(); i++) {
        output.writeInt32(2, heroId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < heroId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(heroId_.get(i));
        }
        size += dataSize;
        size += 1 * getHeroIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code City_pb.CityProcedureAssignReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_CityProcedureAssignReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_CityProcedureAssignReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq.class, com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq.Builder.class);
      }

      // Construct using com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        heroId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_CityProcedureAssignReq_descriptor;
      }

      public com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq getDefaultInstanceForType() {
        return com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq.getDefaultInstance();
      }

      public com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq build() {
        com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq buildPartial() {
        com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq result = new com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          heroId_ = java.util.Collections.unmodifiableList(heroId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.heroId_ = heroId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq) {
          return mergeFrom((com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq other) {
        if (other == com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.heroId_.isEmpty()) {
          if (heroId_.isEmpty()) {
            heroId_ = other.heroId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHeroIdIsMutable();
            heroId_.addAll(other.heroId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 hero_id = 2;
      private java.util.List<java.lang.Integer> heroId_ = java.util.Collections.emptyList();
      private void ensureHeroIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          heroId_ = new java.util.ArrayList<java.lang.Integer>(heroId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 hero_id = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getHeroIdList() {
        return java.util.Collections.unmodifiableList(heroId_);
      }
      /**
       * <code>repeated int32 hero_id = 2;</code>
       */
      public int getHeroIdCount() {
        return heroId_.size();
      }
      /**
       * <code>repeated int32 hero_id = 2;</code>
       */
      public int getHeroId(int index) {
        return heroId_.get(index);
      }
      /**
       * <code>repeated int32 hero_id = 2;</code>
       */
      public Builder setHeroId(
          int index, int value) {
        ensureHeroIdIsMutable();
        heroId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 hero_id = 2;</code>
       */
      public Builder addHeroId(int value) {
        ensureHeroIdIsMutable();
        heroId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 hero_id = 2;</code>
       */
      public Builder addAllHeroId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureHeroIdIsMutable();
        super.addAll(values, heroId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 hero_id = 2;</code>
       */
      public Builder clearHeroId() {
        heroId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:City_pb.CityProcedureAssignReq)
    }

    static {
      defaultInstance = new CityProcedureAssignReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:City_pb.CityProcedureAssignReq)
  }

  public interface PkgGuardReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 slot_id = 1;
    /**
     * <code>optional int32 slot_id = 1;</code>
     */
    boolean hasSlotId();
    /**
     * <code>optional int32 slot_id = 1;</code>
     */
    int getSlotId();

    // optional int32 pkg_id = 2;
    /**
     * <code>optional int32 pkg_id = 2;</code>
     */
    boolean hasPkgId();
    /**
     * <code>optional int32 pkg_id = 2;</code>
     */
    int getPkgId();

    // optional bool is_guard = 3;
    /**
     * <code>optional bool is_guard = 3;</code>
     */
    boolean hasIsGuard();
    /**
     * <code>optional bool is_guard = 3;</code>
     */
    boolean getIsGuard();
  }
  /**
   * Protobuf type {@code City_pb.PkgGuardReq}
   */
  public static final class PkgGuardReq extends
      com.google.protobuf.GeneratedMessage
      implements PkgGuardReqOrBuilder {
    // Use PkgGuardReq.newBuilder() to construct.
    private PkgGuardReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PkgGuardReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PkgGuardReq defaultInstance;
    public static PkgGuardReq getDefaultInstance() {
      return defaultInstance;
    }

    public PkgGuardReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PkgGuardReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              slotId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pkgId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isGuard_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_PkgGuardReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_PkgGuardReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leocool.sgland.protocol.CityMsg.PkgGuardReq.class, com.leocool.sgland.protocol.CityMsg.PkgGuardReq.Builder.class);
    }

    public static com.google.protobuf.Parser<PkgGuardReq> PARSER =
        new com.google.protobuf.AbstractParser<PkgGuardReq>() {
      public PkgGuardReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PkgGuardReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PkgGuardReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 slot_id = 1;
    public static final int SLOT_ID_FIELD_NUMBER = 1;
    private int slotId_;
    /**
     * <code>optional int32 slot_id = 1;</code>
     */
    public boolean hasSlotId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 slot_id = 1;</code>
     */
    public int getSlotId() {
      return slotId_;
    }

    // optional int32 pkg_id = 2;
    public static final int PKG_ID_FIELD_NUMBER = 2;
    private int pkgId_;
    /**
     * <code>optional int32 pkg_id = 2;</code>
     */
    public boolean hasPkgId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 pkg_id = 2;</code>
     */
    public int getPkgId() {
      return pkgId_;
    }

    // optional bool is_guard = 3;
    public static final int IS_GUARD_FIELD_NUMBER = 3;
    private boolean isGuard_;
    /**
     * <code>optional bool is_guard = 3;</code>
     */
    public boolean hasIsGuard() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool is_guard = 3;</code>
     */
    public boolean getIsGuard() {
      return isGuard_;
    }

    private void initFields() {
      slotId_ = 0;
      pkgId_ = 0;
      isGuard_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, slotId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pkgId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isGuard_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, slotId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pkgId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isGuard_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.leocool.sgland.protocol.CityMsg.PkgGuardReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.CityMsg.PkgGuardReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.PkgGuardReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.CityMsg.PkgGuardReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.PkgGuardReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.PkgGuardReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.PkgGuardReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.PkgGuardReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.PkgGuardReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.PkgGuardReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leocool.sgland.protocol.CityMsg.PkgGuardReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code City_pb.PkgGuardReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leocool.sgland.protocol.CityMsg.PkgGuardReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_PkgGuardReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_PkgGuardReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leocool.sgland.protocol.CityMsg.PkgGuardReq.class, com.leocool.sgland.protocol.CityMsg.PkgGuardReq.Builder.class);
      }

      // Construct using com.leocool.sgland.protocol.CityMsg.PkgGuardReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        slotId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pkgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        isGuard_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_PkgGuardReq_descriptor;
      }

      public com.leocool.sgland.protocol.CityMsg.PkgGuardReq getDefaultInstanceForType() {
        return com.leocool.sgland.protocol.CityMsg.PkgGuardReq.getDefaultInstance();
      }

      public com.leocool.sgland.protocol.CityMsg.PkgGuardReq build() {
        com.leocool.sgland.protocol.CityMsg.PkgGuardReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leocool.sgland.protocol.CityMsg.PkgGuardReq buildPartial() {
        com.leocool.sgland.protocol.CityMsg.PkgGuardReq result = new com.leocool.sgland.protocol.CityMsg.PkgGuardReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.slotId_ = slotId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pkgId_ = pkgId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isGuard_ = isGuard_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leocool.sgland.protocol.CityMsg.PkgGuardReq) {
          return mergeFrom((com.leocool.sgland.protocol.CityMsg.PkgGuardReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leocool.sgland.protocol.CityMsg.PkgGuardReq other) {
        if (other == com.leocool.sgland.protocol.CityMsg.PkgGuardReq.getDefaultInstance()) return this;
        if (other.hasSlotId()) {
          setSlotId(other.getSlotId());
        }
        if (other.hasPkgId()) {
          setPkgId(other.getPkgId());
        }
        if (other.hasIsGuard()) {
          setIsGuard(other.getIsGuard());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leocool.sgland.protocol.CityMsg.PkgGuardReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leocool.sgland.protocol.CityMsg.PkgGuardReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 slot_id = 1;
      private int slotId_ ;
      /**
       * <code>optional int32 slot_id = 1;</code>
       */
      public boolean hasSlotId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 slot_id = 1;</code>
       */
      public int getSlotId() {
        return slotId_;
      }
      /**
       * <code>optional int32 slot_id = 1;</code>
       */
      public Builder setSlotId(int value) {
        bitField0_ |= 0x00000001;
        slotId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 slot_id = 1;</code>
       */
      public Builder clearSlotId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        slotId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 pkg_id = 2;
      private int pkgId_ ;
      /**
       * <code>optional int32 pkg_id = 2;</code>
       */
      public boolean hasPkgId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 pkg_id = 2;</code>
       */
      public int getPkgId() {
        return pkgId_;
      }
      /**
       * <code>optional int32 pkg_id = 2;</code>
       */
      public Builder setPkgId(int value) {
        bitField0_ |= 0x00000002;
        pkgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pkg_id = 2;</code>
       */
      public Builder clearPkgId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pkgId_ = 0;
        onChanged();
        return this;
      }

      // optional bool is_guard = 3;
      private boolean isGuard_ ;
      /**
       * <code>optional bool is_guard = 3;</code>
       */
      public boolean hasIsGuard() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool is_guard = 3;</code>
       */
      public boolean getIsGuard() {
        return isGuard_;
      }
      /**
       * <code>optional bool is_guard = 3;</code>
       */
      public Builder setIsGuard(boolean value) {
        bitField0_ |= 0x00000004;
        isGuard_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_guard = 3;</code>
       */
      public Builder clearIsGuard() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isGuard_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:City_pb.PkgGuardReq)
    }

    static {
      defaultInstance = new PkgGuardReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:City_pb.PkgGuardReq)
  }

  public interface SglCityMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code City_pb.SglCityMsg}
   */
  public static final class SglCityMsg extends
      com.google.protobuf.GeneratedMessage
      implements SglCityMsgOrBuilder {
    // Use SglCityMsg.newBuilder() to construct.
    private SglCityMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SglCityMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SglCityMsg defaultInstance;
    public static SglCityMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SglCityMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SglCityMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_SglCityMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_SglCityMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leocool.sgland.protocol.CityMsg.SglCityMsg.class, com.leocool.sgland.protocol.CityMsg.SglCityMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SglCityMsg> PARSER =
        new com.google.protobuf.AbstractParser<SglCityMsg>() {
      public SglCityMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SglCityMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SglCityMsg> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.leocool.sgland.protocol.CityMsg.SglCityMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.CityMsg.SglCityMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.SglCityMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.CityMsg.SglCityMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.SglCityMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.SglCityMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.SglCityMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.SglCityMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.CityMsg.SglCityMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.CityMsg.SglCityMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leocool.sgland.protocol.CityMsg.SglCityMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code City_pb.SglCityMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leocool.sgland.protocol.CityMsg.SglCityMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_SglCityMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_SglCityMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leocool.sgland.protocol.CityMsg.SglCityMsg.class, com.leocool.sgland.protocol.CityMsg.SglCityMsg.Builder.class);
      }

      // Construct using com.leocool.sgland.protocol.CityMsg.SglCityMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leocool.sgland.protocol.CityMsg.internal_static_City_pb_SglCityMsg_descriptor;
      }

      public com.leocool.sgland.protocol.CityMsg.SglCityMsg getDefaultInstanceForType() {
        return com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance();
      }

      public com.leocool.sgland.protocol.CityMsg.SglCityMsg build() {
        com.leocool.sgland.protocol.CityMsg.SglCityMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leocool.sgland.protocol.CityMsg.SglCityMsg buildPartial() {
        com.leocool.sgland.protocol.CityMsg.SglCityMsg result = new com.leocool.sgland.protocol.CityMsg.SglCityMsg(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leocool.sgland.protocol.CityMsg.SglCityMsg) {
          return mergeFrom((com.leocool.sgland.protocol.CityMsg.SglCityMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leocool.sgland.protocol.CityMsg.SglCityMsg other) {
        if (other == com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leocool.sgland.protocol.CityMsg.SglCityMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leocool.sgland.protocol.CityMsg.SglCityMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:City_pb.SglCityMsg)
    }

    static {
      defaultInstance = new SglCityMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:City_pb.SglCityMsg)
    public static final int CITY_GUARD_REQ_FIELD_NUMBER = 400;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        com.leocool.sgland.protocol.CityMsg.CityGuardReq> cityGuardReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          0,
          com.leocool.sgland.protocol.CityMsg.CityGuardReq.class,
          com.leocool.sgland.protocol.CityMsg.CityGuardReq.getDefaultInstance());
    public static final int CITY_PICK_REQ_FIELD_NUMBER = 401;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        java.lang.Integer> cityPickReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          1,
          java.lang.Integer.class,
          null);
    public static final int CITY_PROCEDURE_REMOVE_REQ_FIELD_NUMBER = 402;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        java.lang.Integer> cityProcedureRemoveReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          2,
          java.lang.Integer.class,
          null);
    public static final int CITY_PROCEDURE_FINISH_REQ_FIELD_NUMBER = 403;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        java.lang.Integer> cityProcedureFinishReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          3,
          java.lang.Integer.class,
          null);
    public static final int CITY_PROCEDURE_ASSIGN_REQ_FIELD_NUMBER = 404;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq> cityProcedureAssignReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          4,
          com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq.class,
          com.leocool.sgland.protocol.CityMsg.CityProcedureAssignReq.getDefaultInstance());
    public static final int CITY_VISIT_REMOVE_REQ_FIELD_NUMBER = 405;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        java.lang.Integer> cityVisitRemoveReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          5,
          java.lang.Integer.class,
          null);
    public static final int CITY_VISIT_RECRUIT_REQ_FIELD_NUMBER = 406;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        java.lang.Integer> cityVisitRecruitReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          6,
          java.lang.Integer.class,
          null);
    public static final int CITY_VISIT_STAY_REQ_FIELD_NUMBER = 407;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        java.lang.Integer> cityVisitStayReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          7,
          java.lang.Integer.class,
          null);
    public static final int CITY_PROCEDURE_CANCEL_REQ_FIELD_NUMBER = 408;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        java.lang.Integer> cityProcedureCancelReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          8,
          java.lang.Integer.class,
          null);
    public static final int PKG_GUARD_REQ_FIELD_NUMBER = 409;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        com.leocool.sgland.protocol.CityMsg.PkgGuardReq> pkgGuardReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          9,
          com.leocool.sgland.protocol.CityMsg.PkgGuardReq.class,
          com.leocool.sgland.protocol.CityMsg.PkgGuardReq.getDefaultInstance());
    public static final int CITY_VISIT_RESP_FIELD_NUMBER = 400;
    /**
     * <code>extend .SglMsg_pb.SglRespMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglRespMsg,
        java.util.List<com.leocool.sgland.protocol.Data.Visit>> cityVisitResp = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          10,
          com.leocool.sgland.protocol.Data.Visit.class,
          com.leocool.sgland.protocol.Data.Visit.getDefaultInstance());
    public static final int CITY_GUARD_RESP_FIELD_NUMBER = 401;
    /**
     * <code>extend .SglMsg_pb.SglRespMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglRespMsg,
        com.leocool.sgland.protocol.Data.GuardSlot> cityGuardResp = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          11,
          com.leocool.sgland.protocol.Data.GuardSlot.class,
          com.leocool.sgland.protocol.Data.GuardSlot.getDefaultInstance());
    public static final int CITY_PICK_RESP_FIELD_NUMBER = 402;
    /**
     * <code>extend .SglMsg_pb.SglRespMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglRespMsg,
        com.leocool.sgland.protocol.Data.GuardSlot> cityPickResp = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          12,
          com.leocool.sgland.protocol.Data.GuardSlot.class,
          com.leocool.sgland.protocol.Data.GuardSlot.getDefaultInstance());
    public static final int PKG_GUARD_RESP_FIELD_NUMBER = 403;
    /**
     * <code>extend .SglMsg_pb.SglRespMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglRespMsg,
        com.leocool.sgland.protocol.Data.PkgGuardSlot> pkgGuardResp = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          13,
          com.leocool.sgland.protocol.Data.PkgGuardSlot.class,
          com.leocool.sgland.protocol.Data.PkgGuardSlot.getDefaultInstance());
    public static final int PKG_PICK_RESP_FIELD_NUMBER = 404;
    /**
     * <code>extend .SglMsg_pb.SglRespMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglRespMsg,
        com.leocool.sgland.protocol.Data.PkgGuardSlot> pkgPickResp = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.CityMsg.SglCityMsg.getDefaultInstance(),
          14,
          com.leocool.sgland.protocol.Data.PkgGuardSlot.class,
          com.leocool.sgland.protocol.Data.PkgGuardSlot.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_City_pb_CityGuardReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_City_pb_CityGuardReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_City_pb_CityProcedureAssignReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_City_pb_CityProcedureAssignReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_City_pb_PkgGuardReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_City_pb_PkgGuardReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_City_pb_SglCityMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_City_pb_SglCityMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCity_pb.proto\022\007City_pb\032\017SglMsg_pb.prot" +
      "o\032\rData_pb.proto\"B\n\014CityGuardReq\022\017\n\007slot" +
      "_id\030\001 \001(\005\022\017\n\007info_id\030\002 \001(\005\022\020\n\010is_guard\030\003" +
      " \001(\010\"5\n\026CityProcedureAssignReq\022\n\n\002id\030\001 \001" +
      "(\005\022\017\n\007hero_id\030\002 \003(\005\"@\n\013PkgGuardReq\022\017\n\007sl" +
      "ot_id\030\001 \001(\005\022\016\n\006pkg_id\030\002 \001(\005\022\020\n\010is_guard\030" +
      "\003 \001(\010\"\305\007\n\nSglCityMsg2D\n\016city_guard_req\022\024" +
      ".SglMsg_pb.SglReqMsg\030\220\003 \001(\0132\025.City_pb.Ci" +
      "tyGuardReq2,\n\rcity_pick_req\022\024.SglMsg_pb." +
      "SglReqMsg\030\221\003 \001(\00528\n\031city_procedure_remov",
      "e_req\022\024.SglMsg_pb.SglReqMsg\030\222\003 \001(\00528\n\031ci" +
      "ty_procedure_finish_req\022\024.SglMsg_pb.SglR" +
      "eqMsg\030\223\003 \001(\0052Y\n\031city_procedure_assign_re" +
      "q\022\024.SglMsg_pb.SglReqMsg\030\224\003 \001(\0132\037.City_pb" +
      ".CityProcedureAssignReq24\n\025city_visit_re" +
      "move_req\022\024.SglMsg_pb.SglReqMsg\030\225\003 \001(\00525\n" +
      "\026city_visit_recruit_req\022\024.SglMsg_pb.SglR" +
      "eqMsg\030\226\003 \001(\00522\n\023city_visit_stay_req\022\024.Sg" +
      "lMsg_pb.SglReqMsg\030\227\003 \001(\00528\n\031city_procedu" +
      "re_cancel_req\022\024.SglMsg_pb.SglReqMsg\030\230\003 \001",
      "(\0052B\n\rpkg_guard_req\022\024.SglMsg_pb.SglReqMs" +
      "g\030\231\003 \001(\0132\024.City_pb.PkgGuardReq2?\n\017city_v" +
      "isit_resp\022\025.SglMsg_pb.SglRespMsg\030\220\003 \003(\0132" +
      "\016.Data_pb.Visit2C\n\017city_guard_resp\022\025.Sgl" +
      "Msg_pb.SglRespMsg\030\221\003 \001(\0132\022.Data_pb.Guard" +
      "Slot2B\n\016city_pick_resp\022\025.SglMsg_pb.SglRe" +
      "spMsg\030\222\003 \001(\0132\022.Data_pb.GuardSlot2E\n\016pkg_" +
      "guard_resp\022\025.SglMsg_pb.SglRespMsg\030\223\003 \001(\013" +
      "2\025.Data_pb.PkgGuardSlot2D\n\rpkg_pick_resp" +
      "\022\025.SglMsg_pb.SglRespMsg\030\224\003 \001(\0132\025.Data_pb",
      ".PkgGuardSlotB&\n\033com.leocool.sgland.prot" +
      "ocolB\007CityMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_City_pb_CityGuardReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_City_pb_CityGuardReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_City_pb_CityGuardReq_descriptor,
              new java.lang.String[] { "SlotId", "InfoId", "IsGuard", });
          internal_static_City_pb_CityProcedureAssignReq_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_City_pb_CityProcedureAssignReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_City_pb_CityProcedureAssignReq_descriptor,
              new java.lang.String[] { "Id", "HeroId", });
          internal_static_City_pb_PkgGuardReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_City_pb_PkgGuardReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_City_pb_PkgGuardReq_descriptor,
              new java.lang.String[] { "SlotId", "PkgId", "IsGuard", });
          internal_static_City_pb_SglCityMsg_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_City_pb_SglCityMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_City_pb_SglCityMsg_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.leocool.sgland.protocol.SglMsg.getDescriptor(),
          com.leocool.sgland.protocol.Data.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
