// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Feedback_pb.proto

package com.leocool.sgland.protocol;

public final class FeedbackMsg {
  private FeedbackMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.feedbackReq);
    registry.add(com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.userFacebookReq);
  }
  /**
   * Protobuf enum {@code Feedback_pb.FeedbackType}
   */
  public enum FeedbackType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PB_FEEDBACK_CONSULT = 1;</code>
     */
    PB_FEEDBACK_CONSULT(0, 1),
    /**
     * <code>PB_FEEDBACK_BUG = 2;</code>
     */
    PB_FEEDBACK_BUG(1, 2),
    /**
     * <code>PB_FEEDBACK_COMPLAINT = 3;</code>
     */
    PB_FEEDBACK_COMPLAINT(2, 3),
    /**
     * <code>PB_FEEDBACK_SUGGESTION = 4;</code>
     */
    PB_FEEDBACK_SUGGESTION(3, 4),
    ;

    /**
     * <code>PB_FEEDBACK_CONSULT = 1;</code>
     */
    public static final int PB_FEEDBACK_CONSULT_VALUE = 1;
    /**
     * <code>PB_FEEDBACK_BUG = 2;</code>
     */
    public static final int PB_FEEDBACK_BUG_VALUE = 2;
    /**
     * <code>PB_FEEDBACK_COMPLAINT = 3;</code>
     */
    public static final int PB_FEEDBACK_COMPLAINT_VALUE = 3;
    /**
     * <code>PB_FEEDBACK_SUGGESTION = 4;</code>
     */
    public static final int PB_FEEDBACK_SUGGESTION_VALUE = 4;


    public final int getNumber() { return value; }

    public static FeedbackType valueOf(int value) {
      switch (value) {
        case 1: return PB_FEEDBACK_CONSULT;
        case 2: return PB_FEEDBACK_BUG;
        case 3: return PB_FEEDBACK_COMPLAINT;
        case 4: return PB_FEEDBACK_SUGGESTION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FeedbackType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FeedbackType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FeedbackType>() {
            public FeedbackType findValueByNumber(int number) {
              return FeedbackType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.FeedbackMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final FeedbackType[] VALUES = values();

    public static FeedbackType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FeedbackType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Feedback_pb.FeedbackType)
  }

  public interface FeedbackReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .Feedback_pb.FeedbackType type = 1;
    /**
     * <code>optional .Feedback_pb.FeedbackType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .Feedback_pb.FeedbackType type = 1;</code>
     */
    com.leocool.sgland.protocol.FeedbackMsg.FeedbackType getType();

    // optional string content = 2;
    /**
     * <code>optional string content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code Feedback_pb.FeedbackReq}
   */
  public static final class FeedbackReq extends
      com.google.protobuf.GeneratedMessage
      implements FeedbackReqOrBuilder {
    // Use FeedbackReq.newBuilder() to construct.
    private FeedbackReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FeedbackReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FeedbackReq defaultInstance;
    public static FeedbackReq getDefaultInstance() {
      return defaultInstance;
    }

    public FeedbackReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FeedbackReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.leocool.sgland.protocol.FeedbackMsg.FeedbackType value = com.leocool.sgland.protocol.FeedbackMsg.FeedbackType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.FeedbackMsg.internal_static_Feedback_pb_FeedbackReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leocool.sgland.protocol.FeedbackMsg.internal_static_Feedback_pb_FeedbackReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq.class, com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq.Builder.class);
    }

    public static com.google.protobuf.Parser<FeedbackReq> PARSER =
        new com.google.protobuf.AbstractParser<FeedbackReq>() {
      public FeedbackReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedbackReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FeedbackReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .Feedback_pb.FeedbackType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.leocool.sgland.protocol.FeedbackMsg.FeedbackType type_;
    /**
     * <code>optional .Feedback_pb.FeedbackType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Feedback_pb.FeedbackType type = 1;</code>
     */
    public com.leocool.sgland.protocol.FeedbackMsg.FeedbackType getType() {
      return type_;
    }

    // optional string content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.Object content_;
    /**
     * <code>optional string content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = com.leocool.sgland.protocol.FeedbackMsg.FeedbackType.PB_FEEDBACK_CONSULT;
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Feedback_pb.FeedbackReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leocool.sgland.protocol.FeedbackMsg.FeedbackReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leocool.sgland.protocol.FeedbackMsg.internal_static_Feedback_pb_FeedbackReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leocool.sgland.protocol.FeedbackMsg.internal_static_Feedback_pb_FeedbackReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq.class, com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq.Builder.class);
      }

      // Construct using com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.leocool.sgland.protocol.FeedbackMsg.FeedbackType.PB_FEEDBACK_CONSULT;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leocool.sgland.protocol.FeedbackMsg.internal_static_Feedback_pb_FeedbackReq_descriptor;
      }

      public com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq getDefaultInstanceForType() {
        return com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq.getDefaultInstance();
      }

      public com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq build() {
        com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq buildPartial() {
        com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq result = new com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq) {
          return mergeFrom((com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq other) {
        if (other == com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000002;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .Feedback_pb.FeedbackType type = 1;
      private com.leocool.sgland.protocol.FeedbackMsg.FeedbackType type_ = com.leocool.sgland.protocol.FeedbackMsg.FeedbackType.PB_FEEDBACK_CONSULT;
      /**
       * <code>optional .Feedback_pb.FeedbackType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Feedback_pb.FeedbackType type = 1;</code>
       */
      public com.leocool.sgland.protocol.FeedbackMsg.FeedbackType getType() {
        return type_;
      }
      /**
       * <code>optional .Feedback_pb.FeedbackType type = 1;</code>
       */
      public Builder setType(com.leocool.sgland.protocol.FeedbackMsg.FeedbackType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Feedback_pb.FeedbackType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.leocool.sgland.protocol.FeedbackMsg.FeedbackType.PB_FEEDBACK_CONSULT;
        onChanged();
        return this;
      }

      // optional string content = 2;
      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Feedback_pb.FeedbackReq)
    }

    static {
      defaultInstance = new FeedbackReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Feedback_pb.FeedbackReq)
  }

  public interface SglFeedbackMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Feedback_pb.SglFeedbackMsg}
   */
  public static final class SglFeedbackMsg extends
      com.google.protobuf.GeneratedMessage
      implements SglFeedbackMsgOrBuilder {
    // Use SglFeedbackMsg.newBuilder() to construct.
    private SglFeedbackMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SglFeedbackMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SglFeedbackMsg defaultInstance;
    public static SglFeedbackMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SglFeedbackMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SglFeedbackMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.FeedbackMsg.internal_static_Feedback_pb_SglFeedbackMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leocool.sgland.protocol.FeedbackMsg.internal_static_Feedback_pb_SglFeedbackMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.class, com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SglFeedbackMsg> PARSER =
        new com.google.protobuf.AbstractParser<SglFeedbackMsg>() {
      public SglFeedbackMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SglFeedbackMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SglFeedbackMsg> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Feedback_pb.SglFeedbackMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leocool.sgland.protocol.FeedbackMsg.internal_static_Feedback_pb_SglFeedbackMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leocool.sgland.protocol.FeedbackMsg.internal_static_Feedback_pb_SglFeedbackMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.class, com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.Builder.class);
      }

      // Construct using com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leocool.sgland.protocol.FeedbackMsg.internal_static_Feedback_pb_SglFeedbackMsg_descriptor;
      }

      public com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg getDefaultInstanceForType() {
        return com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.getDefaultInstance();
      }

      public com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg build() {
        com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg buildPartial() {
        com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg result = new com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg) {
          return mergeFrom((com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg other) {
        if (other == com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Feedback_pb.SglFeedbackMsg)
    }

    static {
      defaultInstance = new SglFeedbackMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Feedback_pb.SglFeedbackMsg)
    public static final int FEEDBACK_REQ_FIELD_NUMBER = 1300;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq> feedbackReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.getDefaultInstance(),
          0,
          com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq.class,
          com.leocool.sgland.protocol.FeedbackMsg.FeedbackReq.getDefaultInstance());
    public static final int USER_FACEBOOK_REQ_FIELD_NUMBER = 1301;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        java.lang.String> userFacebookReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.FeedbackMsg.SglFeedbackMsg.getDefaultInstance(),
          1,
          java.lang.String.class,
          null);
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Feedback_pb_FeedbackReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Feedback_pb_FeedbackReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Feedback_pb_SglFeedbackMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Feedback_pb_SglFeedbackMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Feedback_pb.proto\022\013Feedback_pb\032\017SglMsg" +
      "_pb.proto\"G\n\013FeedbackReq\022\'\n\004type\030\001 \001(\0162\031" +
      ".Feedback_pb.FeedbackType\022\017\n\007content\030\002 \001" +
      "(\t\"\211\001\n\016SglFeedbackMsg2E\n\014feedback_req\022\024." +
      "SglMsg_pb.SglReqMsg\030\224\n \001(\0132\030.Feedback_pb" +
      ".FeedbackReq20\n\021user_facebook_req\022\024.SglM" +
      "sg_pb.SglReqMsg\030\225\n \001(\t*s\n\014FeedbackType\022\027" +
      "\n\023PB_FEEDBACK_CONSULT\020\001\022\023\n\017PB_FEEDBACK_B" +
      "UG\020\002\022\031\n\025PB_FEEDBACK_COMPLAINT\020\003\022\032\n\026PB_FE" +
      "EDBACK_SUGGESTION\020\004B*\n\033com.leocool.sglan",
      "d.protocolB\013FeedbackMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Feedback_pb_FeedbackReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Feedback_pb_FeedbackReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Feedback_pb_FeedbackReq_descriptor,
              new java.lang.String[] { "Type", "Content", });
          internal_static_Feedback_pb_SglFeedbackMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Feedback_pb_SglFeedbackMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Feedback_pb_SglFeedbackMsg_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.leocool.sgland.protocol.SglMsg.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
