// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: News_pb.proto

package com.leocool.sgland.protocol;

public final class NewsMsg {
  private NewsMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.newsMaintenanceReq);
    registry.add(com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.newsReceiveResp);
    registry.add(com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.newsAnnouncementResp);
    registry.add(com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.newsMaintenanceResp);
  }
  /**
   * Protobuf enum {@code News_pb.What}
   */
  public enum What
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PB_NEWS_PURCHASE = 1;</code>
     */
    PB_NEWS_PURCHASE(0, 1),
    /**
     * <code>PB_NEWS_WAR_DECLARE = 2;</code>
     */
    PB_NEWS_WAR_DECLARE(1, 2),
    /**
     * <code>PB_NEWS_WAR_WIN = 3;</code>
     */
    PB_NEWS_WAR_WIN(2, 3),
    /**
     * <code>PB_NEWS_WAR_LOSE = 4;</code>
     */
    PB_NEWS_WAR_LOSE(3, 4),
    /**
     * <code>PB_NEWS_ATTACK_WIN = 5;</code>
     */
    PB_NEWS_ATTACK_WIN(4, 5),
    /**
     * <code>PB_NEWS_DEFEND_WIN = 6;</code>
     */
    PB_NEWS_DEFEND_WIN(5, 6),
    /**
     * <code>PB_NEWS_LOTTERY = 7;</code>
     */
    PB_NEWS_LOTTERY(6, 7),
    /**
     * <code>PB_NEWS_MIX = 8;</code>
     */
    PB_NEWS_MIX(7, 8),
    /**
     * <code>PB_NEWS_TRANSFORM = 9;</code>
     */
    PB_NEWS_TRANSFORM(8, 9),
    /**
     * <code>PB_NEWS_EXPEDITION = 10;</code>
     */
    PB_NEWS_EXPEDITION(9, 10),
    /**
     * <code>PB_NEWS_RECRUIT = 11;</code>
     */
    PB_NEWS_RECRUIT(10, 11),
    /**
     * <code>PB_NEWS_VISIT = 12;</code>
     */
    PB_NEWS_VISIT(11, 12),
    /**
     * <code>PB_NEWS_UNION_CREATE = 13;</code>
     */
    PB_NEWS_UNION_CREATE(12, 13),
    /**
     * <code>PB_NEWS_UNION_UPGRADE = 14;</code>
     */
    PB_NEWS_UNION_UPGRADE(13, 14),
    /**
     * <code>PB_NEWS_OPEN_CHEST = 15;</code>
     */
    PB_NEWS_OPEN_CHEST(14, 15),
    /**
     * <code>PB_NEWS_BUY = 16;</code>
     */
    PB_NEWS_BUY(15, 16),
    /**
     * <code>PB_NEWS_RANK = 17;</code>
     */
    PB_NEWS_RANK(16, 17),
    /**
     * <code>PB_NEWS_RANK_LADDER = 18;</code>
     */
    PB_NEWS_RANK_LADDER(17, 18),
    ;

    /**
     * <code>PB_NEWS_PURCHASE = 1;</code>
     */
    public static final int PB_NEWS_PURCHASE_VALUE = 1;
    /**
     * <code>PB_NEWS_WAR_DECLARE = 2;</code>
     */
    public static final int PB_NEWS_WAR_DECLARE_VALUE = 2;
    /**
     * <code>PB_NEWS_WAR_WIN = 3;</code>
     */
    public static final int PB_NEWS_WAR_WIN_VALUE = 3;
    /**
     * <code>PB_NEWS_WAR_LOSE = 4;</code>
     */
    public static final int PB_NEWS_WAR_LOSE_VALUE = 4;
    /**
     * <code>PB_NEWS_ATTACK_WIN = 5;</code>
     */
    public static final int PB_NEWS_ATTACK_WIN_VALUE = 5;
    /**
     * <code>PB_NEWS_DEFEND_WIN = 6;</code>
     */
    public static final int PB_NEWS_DEFEND_WIN_VALUE = 6;
    /**
     * <code>PB_NEWS_LOTTERY = 7;</code>
     */
    public static final int PB_NEWS_LOTTERY_VALUE = 7;
    /**
     * <code>PB_NEWS_MIX = 8;</code>
     */
    public static final int PB_NEWS_MIX_VALUE = 8;
    /**
     * <code>PB_NEWS_TRANSFORM = 9;</code>
     */
    public static final int PB_NEWS_TRANSFORM_VALUE = 9;
    /**
     * <code>PB_NEWS_EXPEDITION = 10;</code>
     */
    public static final int PB_NEWS_EXPEDITION_VALUE = 10;
    /**
     * <code>PB_NEWS_RECRUIT = 11;</code>
     */
    public static final int PB_NEWS_RECRUIT_VALUE = 11;
    /**
     * <code>PB_NEWS_VISIT = 12;</code>
     */
    public static final int PB_NEWS_VISIT_VALUE = 12;
    /**
     * <code>PB_NEWS_UNION_CREATE = 13;</code>
     */
    public static final int PB_NEWS_UNION_CREATE_VALUE = 13;
    /**
     * <code>PB_NEWS_UNION_UPGRADE = 14;</code>
     */
    public static final int PB_NEWS_UNION_UPGRADE_VALUE = 14;
    /**
     * <code>PB_NEWS_OPEN_CHEST = 15;</code>
     */
    public static final int PB_NEWS_OPEN_CHEST_VALUE = 15;
    /**
     * <code>PB_NEWS_BUY = 16;</code>
     */
    public static final int PB_NEWS_BUY_VALUE = 16;
    /**
     * <code>PB_NEWS_RANK = 17;</code>
     */
    public static final int PB_NEWS_RANK_VALUE = 17;
    /**
     * <code>PB_NEWS_RANK_LADDER = 18;</code>
     */
    public static final int PB_NEWS_RANK_LADDER_VALUE = 18;


    public final int getNumber() { return value; }

    public static What valueOf(int value) {
      switch (value) {
        case 1: return PB_NEWS_PURCHASE;
        case 2: return PB_NEWS_WAR_DECLARE;
        case 3: return PB_NEWS_WAR_WIN;
        case 4: return PB_NEWS_WAR_LOSE;
        case 5: return PB_NEWS_ATTACK_WIN;
        case 6: return PB_NEWS_DEFEND_WIN;
        case 7: return PB_NEWS_LOTTERY;
        case 8: return PB_NEWS_MIX;
        case 9: return PB_NEWS_TRANSFORM;
        case 10: return PB_NEWS_EXPEDITION;
        case 11: return PB_NEWS_RECRUIT;
        case 12: return PB_NEWS_VISIT;
        case 13: return PB_NEWS_UNION_CREATE;
        case 14: return PB_NEWS_UNION_UPGRADE;
        case 15: return PB_NEWS_OPEN_CHEST;
        case 16: return PB_NEWS_BUY;
        case 17: return PB_NEWS_RANK;
        case 18: return PB_NEWS_RANK_LADDER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<What>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<What>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<What>() {
            public What findValueByNumber(int number) {
              return What.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.NewsMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final What[] VALUES = values();

    public static What valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private What(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:News_pb.What)
  }

  public interface NewsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .News_pb.What what = 1;
    /**
     * <code>optional .News_pb.What what = 1;</code>
     */
    boolean hasWhat();
    /**
     * <code>optional .News_pb.What what = 1;</code>
     */
    com.leocool.sgland.protocol.NewsMsg.What getWhat();

    // optional int32 param = 2;
    /**
     * <code>optional int32 param = 2;</code>
     */
    boolean hasParam();
    /**
     * <code>optional int32 param = 2;</code>
     */
    int getParam();

    // optional .Data_pb.UserInfo user1 = 3;
    /**
     * <code>optional .Data_pb.UserInfo user1 = 3;</code>
     */
    boolean hasUser1();
    /**
     * <code>optional .Data_pb.UserInfo user1 = 3;</code>
     */
    com.leocool.sgland.protocol.Data.UserInfo getUser1();
    /**
     * <code>optional .Data_pb.UserInfo user1 = 3;</code>
     */
    com.leocool.sgland.protocol.Data.UserInfoOrBuilder getUser1OrBuilder();

    // optional .Data_pb.UserInfo user2 = 4;
    /**
     * <code>optional .Data_pb.UserInfo user2 = 4;</code>
     */
    boolean hasUser2();
    /**
     * <code>optional .Data_pb.UserInfo user2 = 4;</code>
     */
    com.leocool.sgland.protocol.Data.UserInfo getUser2();
    /**
     * <code>optional .Data_pb.UserInfo user2 = 4;</code>
     */
    com.leocool.sgland.protocol.Data.UserInfoOrBuilder getUser2OrBuilder();

    // optional .Data_pb.UnionInfo union1 = 5;
    /**
     * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
     */
    boolean hasUnion1();
    /**
     * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
     */
    com.leocool.sgland.protocol.Data.UnionInfo getUnion1();
    /**
     * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
     */
    com.leocool.sgland.protocol.Data.UnionInfoOrBuilder getUnion1OrBuilder();

    // optional .Data_pb.UnionInfo union2 = 6;
    /**
     * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
     */
    boolean hasUnion2();
    /**
     * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
     */
    com.leocool.sgland.protocol.Data.UnionInfo getUnion2();
    /**
     * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
     */
    com.leocool.sgland.protocol.Data.UnionInfoOrBuilder getUnion2OrBuilder();

    // repeated .Data_pb.Resource resource = 7;
    /**
     * <code>repeated .Data_pb.Resource resource = 7;</code>
     */
    java.util.List<com.leocool.sgland.protocol.Data.Resource> 
        getResourceList();
    /**
     * <code>repeated .Data_pb.Resource resource = 7;</code>
     */
    com.leocool.sgland.protocol.Data.Resource getResource(int index);
    /**
     * <code>repeated .Data_pb.Resource resource = 7;</code>
     */
    int getResourceCount();
    /**
     * <code>repeated .Data_pb.Resource resource = 7;</code>
     */
    java.util.List<? extends com.leocool.sgland.protocol.Data.ResourceOrBuilder> 
        getResourceOrBuilderList();
    /**
     * <code>repeated .Data_pb.Resource resource = 7;</code>
     */
    com.leocool.sgland.protocol.Data.ResourceOrBuilder getResourceOrBuilder(
        int index);

    // optional int64 timestamp = 8;
    /**
     * <code>optional int64 timestamp = 8;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 8;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code News_pb.News}
   */
  public static final class News extends
      com.google.protobuf.GeneratedMessage
      implements NewsOrBuilder {
    // Use News.newBuilder() to construct.
    private News(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private News(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final News defaultInstance;
    public static News getDefaultInstance() {
      return defaultInstance;
    }

    public News getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private News(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.leocool.sgland.protocol.NewsMsg.What value = com.leocool.sgland.protocol.NewsMsg.What.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                what_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              param_ = input.readInt32();
              break;
            }
            case 26: {
              com.leocool.sgland.protocol.Data.UserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = user1_.toBuilder();
              }
              user1_ = input.readMessage(com.leocool.sgland.protocol.Data.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user1_);
                user1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.leocool.sgland.protocol.Data.UserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = user2_.toBuilder();
              }
              user2_ = input.readMessage(com.leocool.sgland.protocol.Data.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user2_);
                user2_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              com.leocool.sgland.protocol.Data.UnionInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = union1_.toBuilder();
              }
              union1_ = input.readMessage(com.leocool.sgland.protocol.Data.UnionInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(union1_);
                union1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              com.leocool.sgland.protocol.Data.UnionInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = union2_.toBuilder();
              }
              union2_ = input.readMessage(com.leocool.sgland.protocol.Data.UnionInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(union2_);
                union2_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                resource_ = new java.util.ArrayList<com.leocool.sgland.protocol.Data.Resource>();
                mutable_bitField0_ |= 0x00000040;
              }
              resource_.add(input.readMessage(com.leocool.sgland.protocol.Data.Resource.PARSER, extensionRegistry));
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          resource_ = java.util.Collections.unmodifiableList(resource_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.NewsMsg.internal_static_News_pb_News_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leocool.sgland.protocol.NewsMsg.internal_static_News_pb_News_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leocool.sgland.protocol.NewsMsg.News.class, com.leocool.sgland.protocol.NewsMsg.News.Builder.class);
    }

    public static com.google.protobuf.Parser<News> PARSER =
        new com.google.protobuf.AbstractParser<News>() {
      public News parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new News(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<News> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .News_pb.What what = 1;
    public static final int WHAT_FIELD_NUMBER = 1;
    private com.leocool.sgland.protocol.NewsMsg.What what_;
    /**
     * <code>optional .News_pb.What what = 1;</code>
     */
    public boolean hasWhat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .News_pb.What what = 1;</code>
     */
    public com.leocool.sgland.protocol.NewsMsg.What getWhat() {
      return what_;
    }

    // optional int32 param = 2;
    public static final int PARAM_FIELD_NUMBER = 2;
    private int param_;
    /**
     * <code>optional int32 param = 2;</code>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 param = 2;</code>
     */
    public int getParam() {
      return param_;
    }

    // optional .Data_pb.UserInfo user1 = 3;
    public static final int USER1_FIELD_NUMBER = 3;
    private com.leocool.sgland.protocol.Data.UserInfo user1_;
    /**
     * <code>optional .Data_pb.UserInfo user1 = 3;</code>
     */
    public boolean hasUser1() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Data_pb.UserInfo user1 = 3;</code>
     */
    public com.leocool.sgland.protocol.Data.UserInfo getUser1() {
      return user1_;
    }
    /**
     * <code>optional .Data_pb.UserInfo user1 = 3;</code>
     */
    public com.leocool.sgland.protocol.Data.UserInfoOrBuilder getUser1OrBuilder() {
      return user1_;
    }

    // optional .Data_pb.UserInfo user2 = 4;
    public static final int USER2_FIELD_NUMBER = 4;
    private com.leocool.sgland.protocol.Data.UserInfo user2_;
    /**
     * <code>optional .Data_pb.UserInfo user2 = 4;</code>
     */
    public boolean hasUser2() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Data_pb.UserInfo user2 = 4;</code>
     */
    public com.leocool.sgland.protocol.Data.UserInfo getUser2() {
      return user2_;
    }
    /**
     * <code>optional .Data_pb.UserInfo user2 = 4;</code>
     */
    public com.leocool.sgland.protocol.Data.UserInfoOrBuilder getUser2OrBuilder() {
      return user2_;
    }

    // optional .Data_pb.UnionInfo union1 = 5;
    public static final int UNION1_FIELD_NUMBER = 5;
    private com.leocool.sgland.protocol.Data.UnionInfo union1_;
    /**
     * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
     */
    public boolean hasUnion1() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
     */
    public com.leocool.sgland.protocol.Data.UnionInfo getUnion1() {
      return union1_;
    }
    /**
     * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
     */
    public com.leocool.sgland.protocol.Data.UnionInfoOrBuilder getUnion1OrBuilder() {
      return union1_;
    }

    // optional .Data_pb.UnionInfo union2 = 6;
    public static final int UNION2_FIELD_NUMBER = 6;
    private com.leocool.sgland.protocol.Data.UnionInfo union2_;
    /**
     * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
     */
    public boolean hasUnion2() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
     */
    public com.leocool.sgland.protocol.Data.UnionInfo getUnion2() {
      return union2_;
    }
    /**
     * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
     */
    public com.leocool.sgland.protocol.Data.UnionInfoOrBuilder getUnion2OrBuilder() {
      return union2_;
    }

    // repeated .Data_pb.Resource resource = 7;
    public static final int RESOURCE_FIELD_NUMBER = 7;
    private java.util.List<com.leocool.sgland.protocol.Data.Resource> resource_;
    /**
     * <code>repeated .Data_pb.Resource resource = 7;</code>
     */
    public java.util.List<com.leocool.sgland.protocol.Data.Resource> getResourceList() {
      return resource_;
    }
    /**
     * <code>repeated .Data_pb.Resource resource = 7;</code>
     */
    public java.util.List<? extends com.leocool.sgland.protocol.Data.ResourceOrBuilder> 
        getResourceOrBuilderList() {
      return resource_;
    }
    /**
     * <code>repeated .Data_pb.Resource resource = 7;</code>
     */
    public int getResourceCount() {
      return resource_.size();
    }
    /**
     * <code>repeated .Data_pb.Resource resource = 7;</code>
     */
    public com.leocool.sgland.protocol.Data.Resource getResource(int index) {
      return resource_.get(index);
    }
    /**
     * <code>repeated .Data_pb.Resource resource = 7;</code>
     */
    public com.leocool.sgland.protocol.Data.ResourceOrBuilder getResourceOrBuilder(
        int index) {
      return resource_.get(index);
    }

    // optional int64 timestamp = 8;
    public static final int TIMESTAMP_FIELD_NUMBER = 8;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 8;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 timestamp = 8;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      what_ = com.leocool.sgland.protocol.NewsMsg.What.PB_NEWS_PURCHASE;
      param_ = 0;
      user1_ = com.leocool.sgland.protocol.Data.UserInfo.getDefaultInstance();
      user2_ = com.leocool.sgland.protocol.Data.UserInfo.getDefaultInstance();
      union1_ = com.leocool.sgland.protocol.Data.UnionInfo.getDefaultInstance();
      union2_ = com.leocool.sgland.protocol.Data.UnionInfo.getDefaultInstance();
      resource_ = java.util.Collections.emptyList();
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, what_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, param_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, user1_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, user2_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, union1_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, union2_);
      }
      for (int i = 0; i < resource_.size(); i++) {
        output.writeMessage(7, resource_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(8, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, what_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, param_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, user1_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, user2_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, union1_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, union2_);
      }
      for (int i = 0; i < resource_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, resource_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.leocool.sgland.protocol.NewsMsg.News parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.NewsMsg.News parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.NewsMsg.News parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.NewsMsg.News parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.NewsMsg.News parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.NewsMsg.News parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.NewsMsg.News parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leocool.sgland.protocol.NewsMsg.News parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.NewsMsg.News parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.NewsMsg.News parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leocool.sgland.protocol.NewsMsg.News prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code News_pb.News}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leocool.sgland.protocol.NewsMsg.NewsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leocool.sgland.protocol.NewsMsg.internal_static_News_pb_News_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leocool.sgland.protocol.NewsMsg.internal_static_News_pb_News_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leocool.sgland.protocol.NewsMsg.News.class, com.leocool.sgland.protocol.NewsMsg.News.Builder.class);
      }

      // Construct using com.leocool.sgland.protocol.NewsMsg.News.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUser1FieldBuilder();
          getUser2FieldBuilder();
          getUnion1FieldBuilder();
          getUnion2FieldBuilder();
          getResourceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        what_ = com.leocool.sgland.protocol.NewsMsg.What.PB_NEWS_PURCHASE;
        bitField0_ = (bitField0_ & ~0x00000001);
        param_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (user1Builder_ == null) {
          user1_ = com.leocool.sgland.protocol.Data.UserInfo.getDefaultInstance();
        } else {
          user1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (user2Builder_ == null) {
          user2_ = com.leocool.sgland.protocol.Data.UserInfo.getDefaultInstance();
        } else {
          user2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (union1Builder_ == null) {
          union1_ = com.leocool.sgland.protocol.Data.UnionInfo.getDefaultInstance();
        } else {
          union1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (union2Builder_ == null) {
          union2_ = com.leocool.sgland.protocol.Data.UnionInfo.getDefaultInstance();
        } else {
          union2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (resourceBuilder_ == null) {
          resource_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          resourceBuilder_.clear();
        }
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leocool.sgland.protocol.NewsMsg.internal_static_News_pb_News_descriptor;
      }

      public com.leocool.sgland.protocol.NewsMsg.News getDefaultInstanceForType() {
        return com.leocool.sgland.protocol.NewsMsg.News.getDefaultInstance();
      }

      public com.leocool.sgland.protocol.NewsMsg.News build() {
        com.leocool.sgland.protocol.NewsMsg.News result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leocool.sgland.protocol.NewsMsg.News buildPartial() {
        com.leocool.sgland.protocol.NewsMsg.News result = new com.leocool.sgland.protocol.NewsMsg.News(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.what_ = what_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.param_ = param_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (user1Builder_ == null) {
          result.user1_ = user1_;
        } else {
          result.user1_ = user1Builder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (user2Builder_ == null) {
          result.user2_ = user2_;
        } else {
          result.user2_ = user2Builder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (union1Builder_ == null) {
          result.union1_ = union1_;
        } else {
          result.union1_ = union1Builder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (union2Builder_ == null) {
          result.union2_ = union2_;
        } else {
          result.union2_ = union2Builder_.build();
        }
        if (resourceBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            resource_ = java.util.Collections.unmodifiableList(resource_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.resource_ = resource_;
        } else {
          result.resource_ = resourceBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leocool.sgland.protocol.NewsMsg.News) {
          return mergeFrom((com.leocool.sgland.protocol.NewsMsg.News)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leocool.sgland.protocol.NewsMsg.News other) {
        if (other == com.leocool.sgland.protocol.NewsMsg.News.getDefaultInstance()) return this;
        if (other.hasWhat()) {
          setWhat(other.getWhat());
        }
        if (other.hasParam()) {
          setParam(other.getParam());
        }
        if (other.hasUser1()) {
          mergeUser1(other.getUser1());
        }
        if (other.hasUser2()) {
          mergeUser2(other.getUser2());
        }
        if (other.hasUnion1()) {
          mergeUnion1(other.getUnion1());
        }
        if (other.hasUnion2()) {
          mergeUnion2(other.getUnion2());
        }
        if (resourceBuilder_ == null) {
          if (!other.resource_.isEmpty()) {
            if (resource_.isEmpty()) {
              resource_ = other.resource_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureResourceIsMutable();
              resource_.addAll(other.resource_);
            }
            onChanged();
          }
        } else {
          if (!other.resource_.isEmpty()) {
            if (resourceBuilder_.isEmpty()) {
              resourceBuilder_.dispose();
              resourceBuilder_ = null;
              resource_ = other.resource_;
              bitField0_ = (bitField0_ & ~0x00000040);
              resourceBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResourceFieldBuilder() : null;
            } else {
              resourceBuilder_.addAllMessages(other.resource_);
            }
          }
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leocool.sgland.protocol.NewsMsg.News parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leocool.sgland.protocol.NewsMsg.News) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .News_pb.What what = 1;
      private com.leocool.sgland.protocol.NewsMsg.What what_ = com.leocool.sgland.protocol.NewsMsg.What.PB_NEWS_PURCHASE;
      /**
       * <code>optional .News_pb.What what = 1;</code>
       */
      public boolean hasWhat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .News_pb.What what = 1;</code>
       */
      public com.leocool.sgland.protocol.NewsMsg.What getWhat() {
        return what_;
      }
      /**
       * <code>optional .News_pb.What what = 1;</code>
       */
      public Builder setWhat(com.leocool.sgland.protocol.NewsMsg.What value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        what_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .News_pb.What what = 1;</code>
       */
      public Builder clearWhat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        what_ = com.leocool.sgland.protocol.NewsMsg.What.PB_NEWS_PURCHASE;
        onChanged();
        return this;
      }

      // optional int32 param = 2;
      private int param_ ;
      /**
       * <code>optional int32 param = 2;</code>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 param = 2;</code>
       */
      public int getParam() {
        return param_;
      }
      /**
       * <code>optional int32 param = 2;</code>
       */
      public Builder setParam(int value) {
        bitField0_ |= 0x00000002;
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 param = 2;</code>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000002);
        param_ = 0;
        onChanged();
        return this;
      }

      // optional .Data_pb.UserInfo user1 = 3;
      private com.leocool.sgland.protocol.Data.UserInfo user1_ = com.leocool.sgland.protocol.Data.UserInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.leocool.sgland.protocol.Data.UserInfo, com.leocool.sgland.protocol.Data.UserInfo.Builder, com.leocool.sgland.protocol.Data.UserInfoOrBuilder> user1Builder_;
      /**
       * <code>optional .Data_pb.UserInfo user1 = 3;</code>
       */
      public boolean hasUser1() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Data_pb.UserInfo user1 = 3;</code>
       */
      public com.leocool.sgland.protocol.Data.UserInfo getUser1() {
        if (user1Builder_ == null) {
          return user1_;
        } else {
          return user1Builder_.getMessage();
        }
      }
      /**
       * <code>optional .Data_pb.UserInfo user1 = 3;</code>
       */
      public Builder setUser1(com.leocool.sgland.protocol.Data.UserInfo value) {
        if (user1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user1_ = value;
          onChanged();
        } else {
          user1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Data_pb.UserInfo user1 = 3;</code>
       */
      public Builder setUser1(
          com.leocool.sgland.protocol.Data.UserInfo.Builder builderForValue) {
        if (user1Builder_ == null) {
          user1_ = builderForValue.build();
          onChanged();
        } else {
          user1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Data_pb.UserInfo user1 = 3;</code>
       */
      public Builder mergeUser1(com.leocool.sgland.protocol.Data.UserInfo value) {
        if (user1Builder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              user1_ != com.leocool.sgland.protocol.Data.UserInfo.getDefaultInstance()) {
            user1_ =
              com.leocool.sgland.protocol.Data.UserInfo.newBuilder(user1_).mergeFrom(value).buildPartial();
          } else {
            user1_ = value;
          }
          onChanged();
        } else {
          user1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Data_pb.UserInfo user1 = 3;</code>
       */
      public Builder clearUser1() {
        if (user1Builder_ == null) {
          user1_ = com.leocool.sgland.protocol.Data.UserInfo.getDefaultInstance();
          onChanged();
        } else {
          user1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Data_pb.UserInfo user1 = 3;</code>
       */
      public com.leocool.sgland.protocol.Data.UserInfo.Builder getUser1Builder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getUser1FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Data_pb.UserInfo user1 = 3;</code>
       */
      public com.leocool.sgland.protocol.Data.UserInfoOrBuilder getUser1OrBuilder() {
        if (user1Builder_ != null) {
          return user1Builder_.getMessageOrBuilder();
        } else {
          return user1_;
        }
      }
      /**
       * <code>optional .Data_pb.UserInfo user1 = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.leocool.sgland.protocol.Data.UserInfo, com.leocool.sgland.protocol.Data.UserInfo.Builder, com.leocool.sgland.protocol.Data.UserInfoOrBuilder> 
          getUser1FieldBuilder() {
        if (user1Builder_ == null) {
          user1Builder_ = new com.google.protobuf.SingleFieldBuilder<
              com.leocool.sgland.protocol.Data.UserInfo, com.leocool.sgland.protocol.Data.UserInfo.Builder, com.leocool.sgland.protocol.Data.UserInfoOrBuilder>(
                  user1_,
                  getParentForChildren(),
                  isClean());
          user1_ = null;
        }
        return user1Builder_;
      }

      // optional .Data_pb.UserInfo user2 = 4;
      private com.leocool.sgland.protocol.Data.UserInfo user2_ = com.leocool.sgland.protocol.Data.UserInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.leocool.sgland.protocol.Data.UserInfo, com.leocool.sgland.protocol.Data.UserInfo.Builder, com.leocool.sgland.protocol.Data.UserInfoOrBuilder> user2Builder_;
      /**
       * <code>optional .Data_pb.UserInfo user2 = 4;</code>
       */
      public boolean hasUser2() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Data_pb.UserInfo user2 = 4;</code>
       */
      public com.leocool.sgland.protocol.Data.UserInfo getUser2() {
        if (user2Builder_ == null) {
          return user2_;
        } else {
          return user2Builder_.getMessage();
        }
      }
      /**
       * <code>optional .Data_pb.UserInfo user2 = 4;</code>
       */
      public Builder setUser2(com.leocool.sgland.protocol.Data.UserInfo value) {
        if (user2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user2_ = value;
          onChanged();
        } else {
          user2Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Data_pb.UserInfo user2 = 4;</code>
       */
      public Builder setUser2(
          com.leocool.sgland.protocol.Data.UserInfo.Builder builderForValue) {
        if (user2Builder_ == null) {
          user2_ = builderForValue.build();
          onChanged();
        } else {
          user2Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Data_pb.UserInfo user2 = 4;</code>
       */
      public Builder mergeUser2(com.leocool.sgland.protocol.Data.UserInfo value) {
        if (user2Builder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              user2_ != com.leocool.sgland.protocol.Data.UserInfo.getDefaultInstance()) {
            user2_ =
              com.leocool.sgland.protocol.Data.UserInfo.newBuilder(user2_).mergeFrom(value).buildPartial();
          } else {
            user2_ = value;
          }
          onChanged();
        } else {
          user2Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Data_pb.UserInfo user2 = 4;</code>
       */
      public Builder clearUser2() {
        if (user2Builder_ == null) {
          user2_ = com.leocool.sgland.protocol.Data.UserInfo.getDefaultInstance();
          onChanged();
        } else {
          user2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Data_pb.UserInfo user2 = 4;</code>
       */
      public com.leocool.sgland.protocol.Data.UserInfo.Builder getUser2Builder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getUser2FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Data_pb.UserInfo user2 = 4;</code>
       */
      public com.leocool.sgland.protocol.Data.UserInfoOrBuilder getUser2OrBuilder() {
        if (user2Builder_ != null) {
          return user2Builder_.getMessageOrBuilder();
        } else {
          return user2_;
        }
      }
      /**
       * <code>optional .Data_pb.UserInfo user2 = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.leocool.sgland.protocol.Data.UserInfo, com.leocool.sgland.protocol.Data.UserInfo.Builder, com.leocool.sgland.protocol.Data.UserInfoOrBuilder> 
          getUser2FieldBuilder() {
        if (user2Builder_ == null) {
          user2Builder_ = new com.google.protobuf.SingleFieldBuilder<
              com.leocool.sgland.protocol.Data.UserInfo, com.leocool.sgland.protocol.Data.UserInfo.Builder, com.leocool.sgland.protocol.Data.UserInfoOrBuilder>(
                  user2_,
                  getParentForChildren(),
                  isClean());
          user2_ = null;
        }
        return user2Builder_;
      }

      // optional .Data_pb.UnionInfo union1 = 5;
      private com.leocool.sgland.protocol.Data.UnionInfo union1_ = com.leocool.sgland.protocol.Data.UnionInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.leocool.sgland.protocol.Data.UnionInfo, com.leocool.sgland.protocol.Data.UnionInfo.Builder, com.leocool.sgland.protocol.Data.UnionInfoOrBuilder> union1Builder_;
      /**
       * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
       */
      public boolean hasUnion1() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
       */
      public com.leocool.sgland.protocol.Data.UnionInfo getUnion1() {
        if (union1Builder_ == null) {
          return union1_;
        } else {
          return union1Builder_.getMessage();
        }
      }
      /**
       * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
       */
      public Builder setUnion1(com.leocool.sgland.protocol.Data.UnionInfo value) {
        if (union1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          union1_ = value;
          onChanged();
        } else {
          union1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
       */
      public Builder setUnion1(
          com.leocool.sgland.protocol.Data.UnionInfo.Builder builderForValue) {
        if (union1Builder_ == null) {
          union1_ = builderForValue.build();
          onChanged();
        } else {
          union1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
       */
      public Builder mergeUnion1(com.leocool.sgland.protocol.Data.UnionInfo value) {
        if (union1Builder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              union1_ != com.leocool.sgland.protocol.Data.UnionInfo.getDefaultInstance()) {
            union1_ =
              com.leocool.sgland.protocol.Data.UnionInfo.newBuilder(union1_).mergeFrom(value).buildPartial();
          } else {
            union1_ = value;
          }
          onChanged();
        } else {
          union1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
       */
      public Builder clearUnion1() {
        if (union1Builder_ == null) {
          union1_ = com.leocool.sgland.protocol.Data.UnionInfo.getDefaultInstance();
          onChanged();
        } else {
          union1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
       */
      public com.leocool.sgland.protocol.Data.UnionInfo.Builder getUnion1Builder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getUnion1FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
       */
      public com.leocool.sgland.protocol.Data.UnionInfoOrBuilder getUnion1OrBuilder() {
        if (union1Builder_ != null) {
          return union1Builder_.getMessageOrBuilder();
        } else {
          return union1_;
        }
      }
      /**
       * <code>optional .Data_pb.UnionInfo union1 = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.leocool.sgland.protocol.Data.UnionInfo, com.leocool.sgland.protocol.Data.UnionInfo.Builder, com.leocool.sgland.protocol.Data.UnionInfoOrBuilder> 
          getUnion1FieldBuilder() {
        if (union1Builder_ == null) {
          union1Builder_ = new com.google.protobuf.SingleFieldBuilder<
              com.leocool.sgland.protocol.Data.UnionInfo, com.leocool.sgland.protocol.Data.UnionInfo.Builder, com.leocool.sgland.protocol.Data.UnionInfoOrBuilder>(
                  union1_,
                  getParentForChildren(),
                  isClean());
          union1_ = null;
        }
        return union1Builder_;
      }

      // optional .Data_pb.UnionInfo union2 = 6;
      private com.leocool.sgland.protocol.Data.UnionInfo union2_ = com.leocool.sgland.protocol.Data.UnionInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.leocool.sgland.protocol.Data.UnionInfo, com.leocool.sgland.protocol.Data.UnionInfo.Builder, com.leocool.sgland.protocol.Data.UnionInfoOrBuilder> union2Builder_;
      /**
       * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
       */
      public boolean hasUnion2() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
       */
      public com.leocool.sgland.protocol.Data.UnionInfo getUnion2() {
        if (union2Builder_ == null) {
          return union2_;
        } else {
          return union2Builder_.getMessage();
        }
      }
      /**
       * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
       */
      public Builder setUnion2(com.leocool.sgland.protocol.Data.UnionInfo value) {
        if (union2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          union2_ = value;
          onChanged();
        } else {
          union2Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
       */
      public Builder setUnion2(
          com.leocool.sgland.protocol.Data.UnionInfo.Builder builderForValue) {
        if (union2Builder_ == null) {
          union2_ = builderForValue.build();
          onChanged();
        } else {
          union2Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
       */
      public Builder mergeUnion2(com.leocool.sgland.protocol.Data.UnionInfo value) {
        if (union2Builder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              union2_ != com.leocool.sgland.protocol.Data.UnionInfo.getDefaultInstance()) {
            union2_ =
              com.leocool.sgland.protocol.Data.UnionInfo.newBuilder(union2_).mergeFrom(value).buildPartial();
          } else {
            union2_ = value;
          }
          onChanged();
        } else {
          union2Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
       */
      public Builder clearUnion2() {
        if (union2Builder_ == null) {
          union2_ = com.leocool.sgland.protocol.Data.UnionInfo.getDefaultInstance();
          onChanged();
        } else {
          union2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
       */
      public com.leocool.sgland.protocol.Data.UnionInfo.Builder getUnion2Builder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getUnion2FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
       */
      public com.leocool.sgland.protocol.Data.UnionInfoOrBuilder getUnion2OrBuilder() {
        if (union2Builder_ != null) {
          return union2Builder_.getMessageOrBuilder();
        } else {
          return union2_;
        }
      }
      /**
       * <code>optional .Data_pb.UnionInfo union2 = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.leocool.sgland.protocol.Data.UnionInfo, com.leocool.sgland.protocol.Data.UnionInfo.Builder, com.leocool.sgland.protocol.Data.UnionInfoOrBuilder> 
          getUnion2FieldBuilder() {
        if (union2Builder_ == null) {
          union2Builder_ = new com.google.protobuf.SingleFieldBuilder<
              com.leocool.sgland.protocol.Data.UnionInfo, com.leocool.sgland.protocol.Data.UnionInfo.Builder, com.leocool.sgland.protocol.Data.UnionInfoOrBuilder>(
                  union2_,
                  getParentForChildren(),
                  isClean());
          union2_ = null;
        }
        return union2Builder_;
      }

      // repeated .Data_pb.Resource resource = 7;
      private java.util.List<com.leocool.sgland.protocol.Data.Resource> resource_ =
        java.util.Collections.emptyList();
      private void ensureResourceIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          resource_ = new java.util.ArrayList<com.leocool.sgland.protocol.Data.Resource>(resource_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.leocool.sgland.protocol.Data.Resource, com.leocool.sgland.protocol.Data.Resource.Builder, com.leocool.sgland.protocol.Data.ResourceOrBuilder> resourceBuilder_;

      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public java.util.List<com.leocool.sgland.protocol.Data.Resource> getResourceList() {
        if (resourceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(resource_);
        } else {
          return resourceBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public int getResourceCount() {
        if (resourceBuilder_ == null) {
          return resource_.size();
        } else {
          return resourceBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public com.leocool.sgland.protocol.Data.Resource getResource(int index) {
        if (resourceBuilder_ == null) {
          return resource_.get(index);
        } else {
          return resourceBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public Builder setResource(
          int index, com.leocool.sgland.protocol.Data.Resource value) {
        if (resourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourceIsMutable();
          resource_.set(index, value);
          onChanged();
        } else {
          resourceBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public Builder setResource(
          int index, com.leocool.sgland.protocol.Data.Resource.Builder builderForValue) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.set(index, builderForValue.build());
          onChanged();
        } else {
          resourceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public Builder addResource(com.leocool.sgland.protocol.Data.Resource value) {
        if (resourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourceIsMutable();
          resource_.add(value);
          onChanged();
        } else {
          resourceBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public Builder addResource(
          int index, com.leocool.sgland.protocol.Data.Resource value) {
        if (resourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourceIsMutable();
          resource_.add(index, value);
          onChanged();
        } else {
          resourceBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public Builder addResource(
          com.leocool.sgland.protocol.Data.Resource.Builder builderForValue) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.add(builderForValue.build());
          onChanged();
        } else {
          resourceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public Builder addResource(
          int index, com.leocool.sgland.protocol.Data.Resource.Builder builderForValue) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.add(index, builderForValue.build());
          onChanged();
        } else {
          resourceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public Builder addAllResource(
          java.lang.Iterable<? extends com.leocool.sgland.protocol.Data.Resource> values) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          super.addAll(values, resource_);
          onChanged();
        } else {
          resourceBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public Builder clearResource() {
        if (resourceBuilder_ == null) {
          resource_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          resourceBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public Builder removeResource(int index) {
        if (resourceBuilder_ == null) {
          ensureResourceIsMutable();
          resource_.remove(index);
          onChanged();
        } else {
          resourceBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public com.leocool.sgland.protocol.Data.Resource.Builder getResourceBuilder(
          int index) {
        return getResourceFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public com.leocool.sgland.protocol.Data.ResourceOrBuilder getResourceOrBuilder(
          int index) {
        if (resourceBuilder_ == null) {
          return resource_.get(index);  } else {
          return resourceBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public java.util.List<? extends com.leocool.sgland.protocol.Data.ResourceOrBuilder> 
           getResourceOrBuilderList() {
        if (resourceBuilder_ != null) {
          return resourceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(resource_);
        }
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public com.leocool.sgland.protocol.Data.Resource.Builder addResourceBuilder() {
        return getResourceFieldBuilder().addBuilder(
            com.leocool.sgland.protocol.Data.Resource.getDefaultInstance());
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public com.leocool.sgland.protocol.Data.Resource.Builder addResourceBuilder(
          int index) {
        return getResourceFieldBuilder().addBuilder(
            index, com.leocool.sgland.protocol.Data.Resource.getDefaultInstance());
      }
      /**
       * <code>repeated .Data_pb.Resource resource = 7;</code>
       */
      public java.util.List<com.leocool.sgland.protocol.Data.Resource.Builder> 
           getResourceBuilderList() {
        return getResourceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.leocool.sgland.protocol.Data.Resource, com.leocool.sgland.protocol.Data.Resource.Builder, com.leocool.sgland.protocol.Data.ResourceOrBuilder> 
          getResourceFieldBuilder() {
        if (resourceBuilder_ == null) {
          resourceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.leocool.sgland.protocol.Data.Resource, com.leocool.sgland.protocol.Data.Resource.Builder, com.leocool.sgland.protocol.Data.ResourceOrBuilder>(
                  resource_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          resource_ = null;
        }
        return resourceBuilder_;
      }

      // optional int64 timestamp = 8;
      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 8;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 timestamp = 8;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 8;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000080;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 8;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:News_pb.News)
    }

    static {
      defaultInstance = new News(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:News_pb.News)
  }

  public interface SglNewsMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code News_pb.SglNewsMsg}
   */
  public static final class SglNewsMsg extends
      com.google.protobuf.GeneratedMessage
      implements SglNewsMsgOrBuilder {
    // Use SglNewsMsg.newBuilder() to construct.
    private SglNewsMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SglNewsMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SglNewsMsg defaultInstance;
    public static SglNewsMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SglNewsMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SglNewsMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.NewsMsg.internal_static_News_pb_SglNewsMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leocool.sgland.protocol.NewsMsg.internal_static_News_pb_SglNewsMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.class, com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SglNewsMsg> PARSER =
        new com.google.protobuf.AbstractParser<SglNewsMsg>() {
      public SglNewsMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SglNewsMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SglNewsMsg> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leocool.sgland.protocol.NewsMsg.SglNewsMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code News_pb.SglNewsMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leocool.sgland.protocol.NewsMsg.SglNewsMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leocool.sgland.protocol.NewsMsg.internal_static_News_pb_SglNewsMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leocool.sgland.protocol.NewsMsg.internal_static_News_pb_SglNewsMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.class, com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.Builder.class);
      }

      // Construct using com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leocool.sgland.protocol.NewsMsg.internal_static_News_pb_SglNewsMsg_descriptor;
      }

      public com.leocool.sgland.protocol.NewsMsg.SglNewsMsg getDefaultInstanceForType() {
        return com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.getDefaultInstance();
      }

      public com.leocool.sgland.protocol.NewsMsg.SglNewsMsg build() {
        com.leocool.sgland.protocol.NewsMsg.SglNewsMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leocool.sgland.protocol.NewsMsg.SglNewsMsg buildPartial() {
        com.leocool.sgland.protocol.NewsMsg.SglNewsMsg result = new com.leocool.sgland.protocol.NewsMsg.SglNewsMsg(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leocool.sgland.protocol.NewsMsg.SglNewsMsg) {
          return mergeFrom((com.leocool.sgland.protocol.NewsMsg.SglNewsMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leocool.sgland.protocol.NewsMsg.SglNewsMsg other) {
        if (other == com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leocool.sgland.protocol.NewsMsg.SglNewsMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leocool.sgland.protocol.NewsMsg.SglNewsMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:News_pb.SglNewsMsg)
    }

    static {
      defaultInstance = new SglNewsMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:News_pb.SglNewsMsg)
    public static final int NEWS_MAINTENANCE_REQ_FIELD_NUMBER = 1600;
    /**
     * <code>extend .SglMsg_pb.SglReqMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglReqMsg,
        java.lang.String> newsMaintenanceReq = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.getDefaultInstance(),
          0,
          java.lang.String.class,
          null);
    public static final int NEWS_RECEIVE_RESP_FIELD_NUMBER = 1600;
    /**
     * <code>extend .SglMsg_pb.SglRespMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglRespMsg,
        java.util.List<com.leocool.sgland.protocol.NewsMsg.News>> newsReceiveResp = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.getDefaultInstance(),
          1,
          com.leocool.sgland.protocol.NewsMsg.News.class,
          com.leocool.sgland.protocol.NewsMsg.News.getDefaultInstance());
    public static final int NEWS_ANNOUNCEMENT_RESP_FIELD_NUMBER = 1601;
    /**
     * <code>extend .SglMsg_pb.SglRespMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglRespMsg,
        java.lang.String> newsAnnouncementResp = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.getDefaultInstance(),
          2,
          java.lang.String.class,
          null);
    public static final int NEWS_MAINTENANCE_RESP_FIELD_NUMBER = 1602;
    /**
     * <code>extend .SglMsg_pb.SglRespMsg { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.leocool.sgland.protocol.SglMsg.SglRespMsg,
        java.lang.String> newsMaintenanceResp = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.leocool.sgland.protocol.NewsMsg.SglNewsMsg.getDefaultInstance(),
          3,
          java.lang.String.class,
          null);
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_News_pb_News_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_News_pb_News_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_News_pb_SglNewsMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_News_pb_SglNewsMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rNews_pb.proto\022\007News_pb\032\017SglMsg_pb.prot" +
      "o\032\rData_pb.proto\"\366\001\n\004News\022\033\n\004what\030\001 \001(\0162" +
      "\r.News_pb.What\022\r\n\005param\030\002 \001(\005\022 \n\005user1\030\003" +
      " \001(\0132\021.Data_pb.UserInfo\022 \n\005user2\030\004 \001(\0132\021" +
      ".Data_pb.UserInfo\022\"\n\006union1\030\005 \001(\0132\022.Data" +
      "_pb.UnionInfo\022\"\n\006union2\030\006 \001(\0132\022.Data_pb." +
      "UnionInfo\022#\n\010resource\030\007 \003(\0132\021.Data_pb.Re" +
      "source\022\021\n\ttimestamp\030\010 \001(\003\"\362\001\n\nSglNewsMsg" +
      "23\n\024news_maintenance_req\022\024.SglMsg_pb.Sgl" +
      "ReqMsg\030\300\014 \001(\t2@\n\021news_receive_resp\022\025.Sgl",
      "Msg_pb.SglRespMsg\030\300\014 \003(\0132\r.News_pb.News2" +
      "6\n\026news_announcement_resp\022\025.SglMsg_pb.Sg" +
      "lRespMsg\030\301\014 \001(\t25\n\025news_maintenance_resp" +
      "\022\025.SglMsg_pb.SglRespMsg\030\302\014 \001(\t*\226\003\n\004What\022" +
      "\024\n\020PB_NEWS_PURCHASE\020\001\022\027\n\023PB_NEWS_WAR_DEC" +
      "LARE\020\002\022\023\n\017PB_NEWS_WAR_WIN\020\003\022\024\n\020PB_NEWS_W" +
      "AR_LOSE\020\004\022\026\n\022PB_NEWS_ATTACK_WIN\020\005\022\026\n\022PB_" +
      "NEWS_DEFEND_WIN\020\006\022\023\n\017PB_NEWS_LOTTERY\020\007\022\017" +
      "\n\013PB_NEWS_MIX\020\010\022\025\n\021PB_NEWS_TRANSFORM\020\t\022\026" +
      "\n\022PB_NEWS_EXPEDITION\020\n\022\023\n\017PB_NEWS_RECRUI",
      "T\020\013\022\021\n\rPB_NEWS_VISIT\020\014\022\030\n\024PB_NEWS_UNION_" +
      "CREATE\020\r\022\031\n\025PB_NEWS_UNION_UPGRADE\020\016\022\026\n\022P" +
      "B_NEWS_OPEN_CHEST\020\017\022\017\n\013PB_NEWS_BUY\020\020\022\020\n\014" +
      "PB_NEWS_RANK\020\021\022\027\n\023PB_NEWS_RANK_LADDER\020\022B" +
      "&\n\033com.leocool.sgland.protocolB\007NewsMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_News_pb_News_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_News_pb_News_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_News_pb_News_descriptor,
              new java.lang.String[] { "What", "Param", "User1", "User2", "Union1", "Union2", "Resource", "Timestamp", });
          internal_static_News_pb_SglNewsMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_News_pb_SglNewsMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_News_pb_SglNewsMsg_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.leocool.sgland.protocol.SglMsg.getDescriptor(),
          com.leocool.sgland.protocol.Data.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
