// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SglMsg_pb.proto

package com.leocool.sgland.protocol;

public final class SglMsg {
  private SglMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code SglMsg_pb.ProtoMsgStatus}
   */
  public enum ProtoMsgStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PB_STATUS_OK = 0;</code>
     */
    PB_STATUS_OK(0, 0),
    /**
     * <code>PB_STATUS_AUTHENTICATION_FAIL = 1;</code>
     */
    PB_STATUS_AUTHENTICATION_FAIL(1, 1),
    /**
     * <code>PB_STATUS_INVALID_ARG = 2;</code>
     */
    PB_STATUS_INVALID_ARG(2, 2),
    /**
     * <code>PB_STATUS_LOGIN_FAIL = 3;</code>
     */
    PB_STATUS_LOGIN_FAIL(3, 3),
    /**
     * <code>PB_STATUS_SERVER_ERROR = 4;</code>
     */
    PB_STATUS_SERVER_ERROR(4, 4),
    /**
     * <code>PB_STATUS_DATA_ERROR = 5;</code>
     */
    PB_STATUS_DATA_ERROR(5, 5),
    /**
     * <code>PB_STATUS_OPPONENT_NOT_FOUND = 6;</code>
     */
    PB_STATUS_OPPONENT_NOT_FOUND(6, 6),
    /**
     * <code>PB_STATUS_OUT_OF_SYNC = 7;</code>
     */
    PB_STATUS_OUT_OF_SYNC(7, 7),
    /**
     * <code>PB_STATUS_LOGIN_ELSEWHERE = 8;</code>
     */
    PB_STATUS_LOGIN_ELSEWHERE(8, 8),
    /**
     * <code>PB_STATUS_USER_OFFLINE = 9;</code>
     */
    PB_STATUS_USER_OFFLINE(9, 9),
    /**
     * <code>PB_STATUS_SERVER_MAINTENANCE = 10;</code>
     */
    PB_STATUS_SERVER_MAINTENANCE(10, 10),
    /**
     * <code>PB_STATUS_USER_UNDER_ATTACK = 11;</code>
     */
    PB_STATUS_USER_UNDER_ATTACK(11, 11),
    /**
     * <code>PB_STATUS_USER_ONLINE = 12;</code>
     */
    PB_STATUS_USER_ONLINE(12, 12),
    /**
     * <code>PB_STATUS_USER_SHILED = 13;</code>
     */
    PB_STATUS_USER_SHILED(13, 13),
    /**
     * <code>PB_STATUS_ILLEGAL_NAME = 14;</code>
     */
    PB_STATUS_ILLEGAL_NAME(14, 14),
    /**
     * <code>PB_STATUS_FRIEND_EXCEEDED = 15;</code>
     */
    PB_STATUS_FRIEND_EXCEEDED(15, 15),
    /**
     * <code>PB_STATUS_NAME_EXISTS = 16;</code>
     */
    PB_STATUS_NAME_EXISTS(16, 16),
    /**
     * <code>PB_STATUS_INVALID_VERSION = 17;</code>
     */
    PB_STATUS_INVALID_VERSION(17, 17),
    /**
     * <code>PB_STATUS_BATTLE_RECOVER = 18;</code>
     */
    PB_STATUS_BATTLE_RECOVER(18, 18),
    /**
     * <code>PB_STATUS_RACE_NOT_PREPARED = 19;</code>
     */
    PB_STATUS_RACE_NOT_PREPARED(19, 19),
    /**
     * <code>PB_STATUS_BATTLE_JOIN_NOT_ALLOWED = 20;</code>
     */
    PB_STATUS_BATTLE_JOIN_NOT_ALLOWED(20, 20),
    /**
     * <code>PB_STATUS_BATTLE_WAIT = 21;</code>
     */
    PB_STATUS_BATTLE_WAIT(21, 21),
    /**
     * <code>PB_STATUS_CITY_FOCUSED = 22;</code>
     */
    PB_STATUS_CITY_FOCUSED(22, 22),
    /**
     * <code>PB_STATUS_ALREADY_IN_UNION = 23;</code>
     */
    PB_STATUS_ALREADY_IN_UNION(23, 23),
    /**
     * <code>PB_STATUS_UNION_CLOSED = 24;</code>
     */
    PB_STATUS_UNION_CLOSED(24, 24),
    /**
     * <code>PB_STATUS_UNION_EXCEEDED = 25;</code>
     */
    PB_STATUS_UNION_EXCEEDED(25, 25),
    /**
     * <code>PB_STATUS_NOT_IN_UNION = 26;</code>
     */
    PB_STATUS_NOT_IN_UNION(26, 26),
    /**
     * <code>PB_STATUS_PRIVILEGE_ERROR = 27;</code>
     */
    PB_STATUS_PRIVILEGE_ERROR(27, 27),
    /**
     * <code>PB_STATUS_WAR_ENDED = 28;</code>
     */
    PB_STATUS_WAR_ENDED(28, 28),
    /**
     * <code>PB_STATUS_WAR_NOT_STARTED = 29;</code>
     */
    PB_STATUS_WAR_NOT_STARTED(29, 29),
    /**
     * <code>PB_STATUS_GIFT_CLAIMED = 30;</code>
     */
    PB_STATUS_GIFT_CLAIMED(30, 30),
    /**
     * <code>PB_STATUS_GIFT_EXPIRED = 31;</code>
     */
    PB_STATUS_GIFT_EXPIRED(31, 31),
    /**
     * <code>PB_STATUS_GIFT_INVALID = 32;</code>
     */
    PB_STATUS_GIFT_INVALID(32, 32),
    /**
     * <code>PB_STATUS_CAMP_DEFEATED = 33;</code>
     */
    PB_STATUS_CAMP_DEFEATED(33, 33),
    /**
     * <code>PB_STATUS_UNION_NOT_ENOUGH_POWER = 34;</code>
     */
    PB_STATUS_UNION_NOT_ENOUGH_POWER(34, 34),
    /**
     * <code>PB_STATUS_UNION_NAME_EXISTS = 35;</code>
     */
    PB_STATUS_UNION_NAME_EXISTS(35, 35),
    /**
     * <code>PB_STATUS_BATTLE_NOT_ENDED = 36;</code>
     */
    PB_STATUS_BATTLE_NOT_ENDED(36, 36),
    /**
     * <code>PB_STATUS_USER_BAN_LOGIN = 37;</code>
     */
    PB_STATUS_USER_BAN_LOGIN(37, 37),
    /**
     * <code>PB_STATUS_UNION_APPLY_NOT_ALLOWED = 38;</code>
     */
    PB_STATUS_UNION_APPLY_NOT_ALLOWED(38, 38),
    /**
     * <code>PB_STATUS_UNION_TAG_EXISTS = 39;</code>
     */
    PB_STATUS_UNION_TAG_EXISTS(39, 39),
    /**
     * <code>PB_STATUS_LET_NOT_FOUND = 40;</code>
     */
    PB_STATUS_LET_NOT_FOUND(40, 40),
    /**
     * <code>PB_STATUS_CO_LEADER_EXCEEDED = 41;</code>
     */
    PB_STATUS_CO_LEADER_EXCEEDED(41, 41),
    /**
     * <code>PB_STATUS_INVALID_RESCUE = 42;</code>
     */
    PB_STATUS_INVALID_RESCUE(42, 42),
    /**
     * <code>PB_STATUS_ERROR_CONNECT_BATTLE_SERVER = 43;</code>
     */
    PB_STATUS_ERROR_CONNECT_BATTLE_SERVER(43, 43),
    /**
     * <code>PB_STATUS_INVALID_TUTORIAL = 44;</code>
     */
    PB_STATUS_INVALID_TUTORIAL(44, 44),
    /**
     * <code>PB_STATUS_BATTLE_ALREADY_SHARED = 45;</code>
     */
    PB_STATUS_BATTLE_ALREADY_SHARED(45, 45),
    /**
     * <code>PB_STATUS_UNION_BOSS_LOCKED = 46;</code>
     */
    PB_STATUS_UNION_BOSS_LOCKED(46, 46),
    /**
     * <code>PB_STATUS_UNION_BOSS_UNLOCKED = 47;</code>
     */
    PB_STATUS_UNION_BOSS_UNLOCKED(47, 47),
    /**
     * <code>PB_STATUS_UNION_BOSS_FOCUSED = 48;</code>
     */
    PB_STATUS_UNION_BOSS_FOCUSED(48, 48),
    /**
     * <code>PB_STATUS_UNION_JOIN_CD = 49;</code>
     */
    PB_STATUS_UNION_JOIN_CD(49, 49),
    /**
     * <code>PB_STATUS_FUND_OWNED = 50;</code>
     */
    PB_STATUS_FUND_OWNED(50, 50),
    /**
     * <code>PB_STATUS_BATTLE_TIMEOUT = 51;</code>
     */
    PB_STATUS_BATTLE_TIMEOUT(51, 51),
    /**
     * <code>PB_STATUS_BATTLE_NOT_ALLOWED = 52;</code>
     */
    PB_STATUS_BATTLE_NOT_ALLOWED(52, 52),
    /**
     * <code>PB_STATUS_ILLEGAL_INVITE_CODE = 53;</code>
     */
    PB_STATUS_ILLEGAL_INVITE_CODE(53, 53),
    /**
     * <code>PB_STATUS_GIFT_DUPLICATE = 54;</code>
     */
    PB_STATUS_GIFT_DUPLICATE(54, 54),
    /**
     * <code>PB_STATUS_MATCH_JOIN_NOT_ALLOWED = 55;</code>
     */
    PB_STATUS_MATCH_JOIN_NOT_ALLOWED(55, 55),
    /**
     * <code>PB_STATUS_MATCH_START_NOT_ALLOWED = 56;</code>
     */
    PB_STATUS_MATCH_START_NOT_ALLOWED(56, 56),
    /**
     * <code>PB_STATUS_ERROR_CREATE_MATCH = 57;</code>
     */
    PB_STATUS_ERROR_CREATE_MATCH(57, 57),
    /**
     * <code>PB_STATUS_MASSWAR_JOIN_NOT_ALLOWED = 58;</code>
     */
    PB_STATUS_MASSWAR_JOIN_NOT_ALLOWED(58, 58),
    /**
     * <code>PB_STATUS_MASSWAR_KICKOUT_NOT_ALLOWED = 59;</code>
     */
    PB_STATUS_MASSWAR_KICKOUT_NOT_ALLOWED(59, 59),
    /**
     * <code>PB_STATUS_MASSWAR_TEAM_TROOP_LOCKED = 60;</code>
     */
    PB_STATUS_MASSWAR_TEAM_TROOP_LOCKED(60, 60),
    /**
     * <code>PB_STATUS_MASSWAR_NOT_IN_TEAM = 61;</code>
     */
    PB_STATUS_MASSWAR_NOT_IN_TEAM(61, 61),
    /**
     * <code>PB_STATUS_MASSWAR_ALREADY_IN_TEAM = 62;</code>
     */
    PB_STATUS_MASSWAR_ALREADY_IN_TEAM(62, 62),
    /**
     * <code>PB_STATUS_MASSWAR_TEAM_NOT_FULL = 63;</code>
     */
    PB_STATUS_MASSWAR_TEAM_NOT_FULL(63, 63),
    /**
     * <code>PB_STATUS_MASSWAR_TROOP_NOT_FULL = 64;</code>
     */
    PB_STATUS_MASSWAR_TROOP_NOT_FULL(64, 64),
    /**
     * <code>PB_STATUS_MASSWAR_CANNOT_LEAVE_TEAM = 65;</code>
     */
    PB_STATUS_MASSWAR_CANNOT_LEAVE_TEAM(65, 65),
    /**
     * <code>PB_STATUS_UNOIN_TAG_TOO_LONG = 66;</code>
     */
    PB_STATUS_UNOIN_TAG_TOO_LONG(66, 66),
    /**
     * <code>PB_STATUS_DARK_DUEL_CANCEL_MATCH = 67;</code>
     */
    PB_STATUS_DARK_DUEL_CANCEL_MATCH(67, 67),
    /**
     * <code>PB_STATUS_PLAYER_CAN_NOT_RESEVICE_GIFT = 68;</code>
     */
    PB_STATUS_PLAYER_CAN_NOT_RESEVICE_GIFT(68, 68),
    /**
     * <code>PB_UNION_MEMBER_IN_TEAM = 69;</code>
     */
    PB_UNION_MEMBER_IN_TEAM(69, 69),
    /**
     * <code>PB_STATUS_ROOM_RECONNECT = 70;</code>
     */
    PB_STATUS_ROOM_RECONNECT(70, 70),
    /**
     * <code>PB_STATUS_SEASON_JOIN_NOT_ALLOWED = 71;</code>
     */
    PB_STATUS_SEASON_JOIN_NOT_ALLOWED(71, 71),
    /**
     * <code>PB_STATUS_SEASON_START_NOT_ALLOWED = 72;</code>
     */
    PB_STATUS_SEASON_START_NOT_ALLOWED(72, 72),
    /**
     * <code>PB_STATUS_REPORT_UPPER_LIMIT = 73;</code>
     */
    PB_STATUS_REPORT_UPPER_LIMIT(73, 73),
    /**
     * <code>PB_STATUS_USER_BAN_BATTLE = 74;</code>
     */
    PB_STATUS_USER_BAN_BATTLE(74, 74),
    /**
     * <code>PB_STATUS_HAS_LEND_CARD_IN_UNION = 75;</code>
     */
    PB_STATUS_HAS_LEND_CARD_IN_UNION(75, 75),
    ;

    /**
     * <code>PB_STATUS_OK = 0;</code>
     */
    public static final int PB_STATUS_OK_VALUE = 0;
    /**
     * <code>PB_STATUS_AUTHENTICATION_FAIL = 1;</code>
     */
    public static final int PB_STATUS_AUTHENTICATION_FAIL_VALUE = 1;
    /**
     * <code>PB_STATUS_INVALID_ARG = 2;</code>
     */
    public static final int PB_STATUS_INVALID_ARG_VALUE = 2;
    /**
     * <code>PB_STATUS_LOGIN_FAIL = 3;</code>
     */
    public static final int PB_STATUS_LOGIN_FAIL_VALUE = 3;
    /**
     * <code>PB_STATUS_SERVER_ERROR = 4;</code>
     */
    public static final int PB_STATUS_SERVER_ERROR_VALUE = 4;
    /**
     * <code>PB_STATUS_DATA_ERROR = 5;</code>
     */
    public static final int PB_STATUS_DATA_ERROR_VALUE = 5;
    /**
     * <code>PB_STATUS_OPPONENT_NOT_FOUND = 6;</code>
     */
    public static final int PB_STATUS_OPPONENT_NOT_FOUND_VALUE = 6;
    /**
     * <code>PB_STATUS_OUT_OF_SYNC = 7;</code>
     */
    public static final int PB_STATUS_OUT_OF_SYNC_VALUE = 7;
    /**
     * <code>PB_STATUS_LOGIN_ELSEWHERE = 8;</code>
     */
    public static final int PB_STATUS_LOGIN_ELSEWHERE_VALUE = 8;
    /**
     * <code>PB_STATUS_USER_OFFLINE = 9;</code>
     */
    public static final int PB_STATUS_USER_OFFLINE_VALUE = 9;
    /**
     * <code>PB_STATUS_SERVER_MAINTENANCE = 10;</code>
     */
    public static final int PB_STATUS_SERVER_MAINTENANCE_VALUE = 10;
    /**
     * <code>PB_STATUS_USER_UNDER_ATTACK = 11;</code>
     */
    public static final int PB_STATUS_USER_UNDER_ATTACK_VALUE = 11;
    /**
     * <code>PB_STATUS_USER_ONLINE = 12;</code>
     */
    public static final int PB_STATUS_USER_ONLINE_VALUE = 12;
    /**
     * <code>PB_STATUS_USER_SHILED = 13;</code>
     */
    public static final int PB_STATUS_USER_SHILED_VALUE = 13;
    /**
     * <code>PB_STATUS_ILLEGAL_NAME = 14;</code>
     */
    public static final int PB_STATUS_ILLEGAL_NAME_VALUE = 14;
    /**
     * <code>PB_STATUS_FRIEND_EXCEEDED = 15;</code>
     */
    public static final int PB_STATUS_FRIEND_EXCEEDED_VALUE = 15;
    /**
     * <code>PB_STATUS_NAME_EXISTS = 16;</code>
     */
    public static final int PB_STATUS_NAME_EXISTS_VALUE = 16;
    /**
     * <code>PB_STATUS_INVALID_VERSION = 17;</code>
     */
    public static final int PB_STATUS_INVALID_VERSION_VALUE = 17;
    /**
     * <code>PB_STATUS_BATTLE_RECOVER = 18;</code>
     */
    public static final int PB_STATUS_BATTLE_RECOVER_VALUE = 18;
    /**
     * <code>PB_STATUS_RACE_NOT_PREPARED = 19;</code>
     */
    public static final int PB_STATUS_RACE_NOT_PREPARED_VALUE = 19;
    /**
     * <code>PB_STATUS_BATTLE_JOIN_NOT_ALLOWED = 20;</code>
     */
    public static final int PB_STATUS_BATTLE_JOIN_NOT_ALLOWED_VALUE = 20;
    /**
     * <code>PB_STATUS_BATTLE_WAIT = 21;</code>
     */
    public static final int PB_STATUS_BATTLE_WAIT_VALUE = 21;
    /**
     * <code>PB_STATUS_CITY_FOCUSED = 22;</code>
     */
    public static final int PB_STATUS_CITY_FOCUSED_VALUE = 22;
    /**
     * <code>PB_STATUS_ALREADY_IN_UNION = 23;</code>
     */
    public static final int PB_STATUS_ALREADY_IN_UNION_VALUE = 23;
    /**
     * <code>PB_STATUS_UNION_CLOSED = 24;</code>
     */
    public static final int PB_STATUS_UNION_CLOSED_VALUE = 24;
    /**
     * <code>PB_STATUS_UNION_EXCEEDED = 25;</code>
     */
    public static final int PB_STATUS_UNION_EXCEEDED_VALUE = 25;
    /**
     * <code>PB_STATUS_NOT_IN_UNION = 26;</code>
     */
    public static final int PB_STATUS_NOT_IN_UNION_VALUE = 26;
    /**
     * <code>PB_STATUS_PRIVILEGE_ERROR = 27;</code>
     */
    public static final int PB_STATUS_PRIVILEGE_ERROR_VALUE = 27;
    /**
     * <code>PB_STATUS_WAR_ENDED = 28;</code>
     */
    public static final int PB_STATUS_WAR_ENDED_VALUE = 28;
    /**
     * <code>PB_STATUS_WAR_NOT_STARTED = 29;</code>
     */
    public static final int PB_STATUS_WAR_NOT_STARTED_VALUE = 29;
    /**
     * <code>PB_STATUS_GIFT_CLAIMED = 30;</code>
     */
    public static final int PB_STATUS_GIFT_CLAIMED_VALUE = 30;
    /**
     * <code>PB_STATUS_GIFT_EXPIRED = 31;</code>
     */
    public static final int PB_STATUS_GIFT_EXPIRED_VALUE = 31;
    /**
     * <code>PB_STATUS_GIFT_INVALID = 32;</code>
     */
    public static final int PB_STATUS_GIFT_INVALID_VALUE = 32;
    /**
     * <code>PB_STATUS_CAMP_DEFEATED = 33;</code>
     */
    public static final int PB_STATUS_CAMP_DEFEATED_VALUE = 33;
    /**
     * <code>PB_STATUS_UNION_NOT_ENOUGH_POWER = 34;</code>
     */
    public static final int PB_STATUS_UNION_NOT_ENOUGH_POWER_VALUE = 34;
    /**
     * <code>PB_STATUS_UNION_NAME_EXISTS = 35;</code>
     */
    public static final int PB_STATUS_UNION_NAME_EXISTS_VALUE = 35;
    /**
     * <code>PB_STATUS_BATTLE_NOT_ENDED = 36;</code>
     */
    public static final int PB_STATUS_BATTLE_NOT_ENDED_VALUE = 36;
    /**
     * <code>PB_STATUS_USER_BAN_LOGIN = 37;</code>
     */
    public static final int PB_STATUS_USER_BAN_LOGIN_VALUE = 37;
    /**
     * <code>PB_STATUS_UNION_APPLY_NOT_ALLOWED = 38;</code>
     */
    public static final int PB_STATUS_UNION_APPLY_NOT_ALLOWED_VALUE = 38;
    /**
     * <code>PB_STATUS_UNION_TAG_EXISTS = 39;</code>
     */
    public static final int PB_STATUS_UNION_TAG_EXISTS_VALUE = 39;
    /**
     * <code>PB_STATUS_LET_NOT_FOUND = 40;</code>
     */
    public static final int PB_STATUS_LET_NOT_FOUND_VALUE = 40;
    /**
     * <code>PB_STATUS_CO_LEADER_EXCEEDED = 41;</code>
     */
    public static final int PB_STATUS_CO_LEADER_EXCEEDED_VALUE = 41;
    /**
     * <code>PB_STATUS_INVALID_RESCUE = 42;</code>
     */
    public static final int PB_STATUS_INVALID_RESCUE_VALUE = 42;
    /**
     * <code>PB_STATUS_ERROR_CONNECT_BATTLE_SERVER = 43;</code>
     */
    public static final int PB_STATUS_ERROR_CONNECT_BATTLE_SERVER_VALUE = 43;
    /**
     * <code>PB_STATUS_INVALID_TUTORIAL = 44;</code>
     */
    public static final int PB_STATUS_INVALID_TUTORIAL_VALUE = 44;
    /**
     * <code>PB_STATUS_BATTLE_ALREADY_SHARED = 45;</code>
     */
    public static final int PB_STATUS_BATTLE_ALREADY_SHARED_VALUE = 45;
    /**
     * <code>PB_STATUS_UNION_BOSS_LOCKED = 46;</code>
     */
    public static final int PB_STATUS_UNION_BOSS_LOCKED_VALUE = 46;
    /**
     * <code>PB_STATUS_UNION_BOSS_UNLOCKED = 47;</code>
     */
    public static final int PB_STATUS_UNION_BOSS_UNLOCKED_VALUE = 47;
    /**
     * <code>PB_STATUS_UNION_BOSS_FOCUSED = 48;</code>
     */
    public static final int PB_STATUS_UNION_BOSS_FOCUSED_VALUE = 48;
    /**
     * <code>PB_STATUS_UNION_JOIN_CD = 49;</code>
     */
    public static final int PB_STATUS_UNION_JOIN_CD_VALUE = 49;
    /**
     * <code>PB_STATUS_FUND_OWNED = 50;</code>
     */
    public static final int PB_STATUS_FUND_OWNED_VALUE = 50;
    /**
     * <code>PB_STATUS_BATTLE_TIMEOUT = 51;</code>
     */
    public static final int PB_STATUS_BATTLE_TIMEOUT_VALUE = 51;
    /**
     * <code>PB_STATUS_BATTLE_NOT_ALLOWED = 52;</code>
     */
    public static final int PB_STATUS_BATTLE_NOT_ALLOWED_VALUE = 52;
    /**
     * <code>PB_STATUS_ILLEGAL_INVITE_CODE = 53;</code>
     */
    public static final int PB_STATUS_ILLEGAL_INVITE_CODE_VALUE = 53;
    /**
     * <code>PB_STATUS_GIFT_DUPLICATE = 54;</code>
     */
    public static final int PB_STATUS_GIFT_DUPLICATE_VALUE = 54;
    /**
     * <code>PB_STATUS_MATCH_JOIN_NOT_ALLOWED = 55;</code>
     */
    public static final int PB_STATUS_MATCH_JOIN_NOT_ALLOWED_VALUE = 55;
    /**
     * <code>PB_STATUS_MATCH_START_NOT_ALLOWED = 56;</code>
     */
    public static final int PB_STATUS_MATCH_START_NOT_ALLOWED_VALUE = 56;
    /**
     * <code>PB_STATUS_ERROR_CREATE_MATCH = 57;</code>
     */
    public static final int PB_STATUS_ERROR_CREATE_MATCH_VALUE = 57;
    /**
     * <code>PB_STATUS_MASSWAR_JOIN_NOT_ALLOWED = 58;</code>
     */
    public static final int PB_STATUS_MASSWAR_JOIN_NOT_ALLOWED_VALUE = 58;
    /**
     * <code>PB_STATUS_MASSWAR_KICKOUT_NOT_ALLOWED = 59;</code>
     */
    public static final int PB_STATUS_MASSWAR_KICKOUT_NOT_ALLOWED_VALUE = 59;
    /**
     * <code>PB_STATUS_MASSWAR_TEAM_TROOP_LOCKED = 60;</code>
     */
    public static final int PB_STATUS_MASSWAR_TEAM_TROOP_LOCKED_VALUE = 60;
    /**
     * <code>PB_STATUS_MASSWAR_NOT_IN_TEAM = 61;</code>
     */
    public static final int PB_STATUS_MASSWAR_NOT_IN_TEAM_VALUE = 61;
    /**
     * <code>PB_STATUS_MASSWAR_ALREADY_IN_TEAM = 62;</code>
     */
    public static final int PB_STATUS_MASSWAR_ALREADY_IN_TEAM_VALUE = 62;
    /**
     * <code>PB_STATUS_MASSWAR_TEAM_NOT_FULL = 63;</code>
     */
    public static final int PB_STATUS_MASSWAR_TEAM_NOT_FULL_VALUE = 63;
    /**
     * <code>PB_STATUS_MASSWAR_TROOP_NOT_FULL = 64;</code>
     */
    public static final int PB_STATUS_MASSWAR_TROOP_NOT_FULL_VALUE = 64;
    /**
     * <code>PB_STATUS_MASSWAR_CANNOT_LEAVE_TEAM = 65;</code>
     */
    public static final int PB_STATUS_MASSWAR_CANNOT_LEAVE_TEAM_VALUE = 65;
    /**
     * <code>PB_STATUS_UNOIN_TAG_TOO_LONG = 66;</code>
     */
    public static final int PB_STATUS_UNOIN_TAG_TOO_LONG_VALUE = 66;
    /**
     * <code>PB_STATUS_DARK_DUEL_CANCEL_MATCH = 67;</code>
     */
    public static final int PB_STATUS_DARK_DUEL_CANCEL_MATCH_VALUE = 67;
    /**
     * <code>PB_STATUS_PLAYER_CAN_NOT_RESEVICE_GIFT = 68;</code>
     */
    public static final int PB_STATUS_PLAYER_CAN_NOT_RESEVICE_GIFT_VALUE = 68;
    /**
     * <code>PB_UNION_MEMBER_IN_TEAM = 69;</code>
     */
    public static final int PB_UNION_MEMBER_IN_TEAM_VALUE = 69;
    /**
     * <code>PB_STATUS_ROOM_RECONNECT = 70;</code>
     */
    public static final int PB_STATUS_ROOM_RECONNECT_VALUE = 70;
    /**
     * <code>PB_STATUS_SEASON_JOIN_NOT_ALLOWED = 71;</code>
     */
    public static final int PB_STATUS_SEASON_JOIN_NOT_ALLOWED_VALUE = 71;
    /**
     * <code>PB_STATUS_SEASON_START_NOT_ALLOWED = 72;</code>
     */
    public static final int PB_STATUS_SEASON_START_NOT_ALLOWED_VALUE = 72;
    /**
     * <code>PB_STATUS_REPORT_UPPER_LIMIT = 73;</code>
     */
    public static final int PB_STATUS_REPORT_UPPER_LIMIT_VALUE = 73;
    /**
     * <code>PB_STATUS_USER_BAN_BATTLE = 74;</code>
     */
    public static final int PB_STATUS_USER_BAN_BATTLE_VALUE = 74;
    /**
     * <code>PB_STATUS_HAS_LEND_CARD_IN_UNION = 75;</code>
     */
    public static final int PB_STATUS_HAS_LEND_CARD_IN_UNION_VALUE = 75;


    public final int getNumber() { return value; }

    public static ProtoMsgStatus valueOf(int value) {
      switch (value) {
        case 0: return PB_STATUS_OK;
        case 1: return PB_STATUS_AUTHENTICATION_FAIL;
        case 2: return PB_STATUS_INVALID_ARG;
        case 3: return PB_STATUS_LOGIN_FAIL;
        case 4: return PB_STATUS_SERVER_ERROR;
        case 5: return PB_STATUS_DATA_ERROR;
        case 6: return PB_STATUS_OPPONENT_NOT_FOUND;
        case 7: return PB_STATUS_OUT_OF_SYNC;
        case 8: return PB_STATUS_LOGIN_ELSEWHERE;
        case 9: return PB_STATUS_USER_OFFLINE;
        case 10: return PB_STATUS_SERVER_MAINTENANCE;
        case 11: return PB_STATUS_USER_UNDER_ATTACK;
        case 12: return PB_STATUS_USER_ONLINE;
        case 13: return PB_STATUS_USER_SHILED;
        case 14: return PB_STATUS_ILLEGAL_NAME;
        case 15: return PB_STATUS_FRIEND_EXCEEDED;
        case 16: return PB_STATUS_NAME_EXISTS;
        case 17: return PB_STATUS_INVALID_VERSION;
        case 18: return PB_STATUS_BATTLE_RECOVER;
        case 19: return PB_STATUS_RACE_NOT_PREPARED;
        case 20: return PB_STATUS_BATTLE_JOIN_NOT_ALLOWED;
        case 21: return PB_STATUS_BATTLE_WAIT;
        case 22: return PB_STATUS_CITY_FOCUSED;
        case 23: return PB_STATUS_ALREADY_IN_UNION;
        case 24: return PB_STATUS_UNION_CLOSED;
        case 25: return PB_STATUS_UNION_EXCEEDED;
        case 26: return PB_STATUS_NOT_IN_UNION;
        case 27: return PB_STATUS_PRIVILEGE_ERROR;
        case 28: return PB_STATUS_WAR_ENDED;
        case 29: return PB_STATUS_WAR_NOT_STARTED;
        case 30: return PB_STATUS_GIFT_CLAIMED;
        case 31: return PB_STATUS_GIFT_EXPIRED;
        case 32: return PB_STATUS_GIFT_INVALID;
        case 33: return PB_STATUS_CAMP_DEFEATED;
        case 34: return PB_STATUS_UNION_NOT_ENOUGH_POWER;
        case 35: return PB_STATUS_UNION_NAME_EXISTS;
        case 36: return PB_STATUS_BATTLE_NOT_ENDED;
        case 37: return PB_STATUS_USER_BAN_LOGIN;
        case 38: return PB_STATUS_UNION_APPLY_NOT_ALLOWED;
        case 39: return PB_STATUS_UNION_TAG_EXISTS;
        case 40: return PB_STATUS_LET_NOT_FOUND;
        case 41: return PB_STATUS_CO_LEADER_EXCEEDED;
        case 42: return PB_STATUS_INVALID_RESCUE;
        case 43: return PB_STATUS_ERROR_CONNECT_BATTLE_SERVER;
        case 44: return PB_STATUS_INVALID_TUTORIAL;
        case 45: return PB_STATUS_BATTLE_ALREADY_SHARED;
        case 46: return PB_STATUS_UNION_BOSS_LOCKED;
        case 47: return PB_STATUS_UNION_BOSS_UNLOCKED;
        case 48: return PB_STATUS_UNION_BOSS_FOCUSED;
        case 49: return PB_STATUS_UNION_JOIN_CD;
        case 50: return PB_STATUS_FUND_OWNED;
        case 51: return PB_STATUS_BATTLE_TIMEOUT;
        case 52: return PB_STATUS_BATTLE_NOT_ALLOWED;
        case 53: return PB_STATUS_ILLEGAL_INVITE_CODE;
        case 54: return PB_STATUS_GIFT_DUPLICATE;
        case 55: return PB_STATUS_MATCH_JOIN_NOT_ALLOWED;
        case 56: return PB_STATUS_MATCH_START_NOT_ALLOWED;
        case 57: return PB_STATUS_ERROR_CREATE_MATCH;
        case 58: return PB_STATUS_MASSWAR_JOIN_NOT_ALLOWED;
        case 59: return PB_STATUS_MASSWAR_KICKOUT_NOT_ALLOWED;
        case 60: return PB_STATUS_MASSWAR_TEAM_TROOP_LOCKED;
        case 61: return PB_STATUS_MASSWAR_NOT_IN_TEAM;
        case 62: return PB_STATUS_MASSWAR_ALREADY_IN_TEAM;
        case 63: return PB_STATUS_MASSWAR_TEAM_NOT_FULL;
        case 64: return PB_STATUS_MASSWAR_TROOP_NOT_FULL;
        case 65: return PB_STATUS_MASSWAR_CANNOT_LEAVE_TEAM;
        case 66: return PB_STATUS_UNOIN_TAG_TOO_LONG;
        case 67: return PB_STATUS_DARK_DUEL_CANCEL_MATCH;
        case 68: return PB_STATUS_PLAYER_CAN_NOT_RESEVICE_GIFT;
        case 69: return PB_UNION_MEMBER_IN_TEAM;
        case 70: return PB_STATUS_ROOM_RECONNECT;
        case 71: return PB_STATUS_SEASON_JOIN_NOT_ALLOWED;
        case 72: return PB_STATUS_SEASON_START_NOT_ALLOWED;
        case 73: return PB_STATUS_REPORT_UPPER_LIMIT;
        case 74: return PB_STATUS_USER_BAN_BATTLE;
        case 75: return PB_STATUS_HAS_LEND_CARD_IN_UNION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtoMsgStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtoMsgStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtoMsgStatus>() {
            public ProtoMsgStatus findValueByNumber(int number) {
              return ProtoMsgStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.SglMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtoMsgStatus[] VALUES = values();

    public static ProtoMsgStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ProtoMsgStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SglMsg_pb.ProtoMsgStatus)
  }

  /**
   * Protobuf enum {@code SglMsg_pb.UserType}
   */
  public enum UserType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PB_USER_CHAPTER = 1;</code>
     */
    PB_USER_CHAPTER(0, 1),
    /**
     * <code>PB_USER_PLAYER = 2;</code>
     */
    PB_USER_PLAYER(1, 2),
    /**
     * <code>PB_USER_NPC = 3;</code>
     */
    PB_USER_NPC(2, 3),
    ;

    /**
     * <code>PB_USER_CHAPTER = 1;</code>
     */
    public static final int PB_USER_CHAPTER_VALUE = 1;
    /**
     * <code>PB_USER_PLAYER = 2;</code>
     */
    public static final int PB_USER_PLAYER_VALUE = 2;
    /**
     * <code>PB_USER_NPC = 3;</code>
     */
    public static final int PB_USER_NPC_VALUE = 3;


    public final int getNumber() { return value; }

    public static UserType valueOf(int value) {
      switch (value) {
        case 1: return PB_USER_CHAPTER;
        case 2: return PB_USER_PLAYER;
        case 3: return PB_USER_NPC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
            public UserType findValueByNumber(int number) {
              return UserType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.SglMsg.getDescriptor().getEnumTypes().get(1);
    }

    private static final UserType[] VALUES = values();

    public static UserType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private UserType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SglMsg_pb.UserType)
  }

  /**
   * Protobuf enum {@code SglMsg_pb.FocusStatus}
   */
  public enum FocusStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PB_FOCUS_SWEEP = 1;</code>
     */
    PB_FOCUS_SWEEP(0, 1),
    /**
     * <code>PB_FOCUS_ATTACK = 2;</code>
     */
    PB_FOCUS_ATTACK(1, 2),
    /**
     * <code>PB_FOCUS_CHALLENGE = 3;</code>
     */
    PB_FOCUS_CHALLENGE(2, 3),
    /**
     * <code>PB_FOCUS_RESCUE = 4;</code>
     */
    PB_FOCUS_RESCUE(3, 4),
    /**
     * <code>PB_FOCUS_LOCK = 5;</code>
     */
    PB_FOCUS_LOCK(4, 5),
    ;

    /**
     * <code>PB_FOCUS_SWEEP = 1;</code>
     */
    public static final int PB_FOCUS_SWEEP_VALUE = 1;
    /**
     * <code>PB_FOCUS_ATTACK = 2;</code>
     */
    public static final int PB_FOCUS_ATTACK_VALUE = 2;
    /**
     * <code>PB_FOCUS_CHALLENGE = 3;</code>
     */
    public static final int PB_FOCUS_CHALLENGE_VALUE = 3;
    /**
     * <code>PB_FOCUS_RESCUE = 4;</code>
     */
    public static final int PB_FOCUS_RESCUE_VALUE = 4;
    /**
     * <code>PB_FOCUS_LOCK = 5;</code>
     */
    public static final int PB_FOCUS_LOCK_VALUE = 5;


    public final int getNumber() { return value; }

    public static FocusStatus valueOf(int value) {
      switch (value) {
        case 1: return PB_FOCUS_SWEEP;
        case 2: return PB_FOCUS_ATTACK;
        case 3: return PB_FOCUS_CHALLENGE;
        case 4: return PB_FOCUS_RESCUE;
        case 5: return PB_FOCUS_LOCK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FocusStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FocusStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FocusStatus>() {
            public FocusStatus findValueByNumber(int number) {
              return FocusStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.SglMsg.getDescriptor().getEnumTypes().get(2);
    }

    private static final FocusStatus[] VALUES = values();

    public static FocusStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FocusStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SglMsg_pb.FocusStatus)
  }

  /**
   * Protobuf enum {@code SglMsg_pb.InviteStatus}
   */
  public enum InviteStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PB_INVITE_INVITED = 0;</code>
     */
    PB_INVITE_INVITED(0, 0),
    /**
     * <code>PB_INVITE_ACCEPTED = 1;</code>
     */
    PB_INVITE_ACCEPTED(1, 1),
    /**
     * <code>PB_INVITE_REFUSED = 2;</code>
     */
    PB_INVITE_REFUSED(2, 2),
    /**
     * <code>PB_INVITE_OK = 3;</code>
     */
    PB_INVITE_OK(3, 3),
    ;

    /**
     * <code>PB_INVITE_INVITED = 0;</code>
     */
    public static final int PB_INVITE_INVITED_VALUE = 0;
    /**
     * <code>PB_INVITE_ACCEPTED = 1;</code>
     */
    public static final int PB_INVITE_ACCEPTED_VALUE = 1;
    /**
     * <code>PB_INVITE_REFUSED = 2;</code>
     */
    public static final int PB_INVITE_REFUSED_VALUE = 2;
    /**
     * <code>PB_INVITE_OK = 3;</code>
     */
    public static final int PB_INVITE_OK_VALUE = 3;


    public final int getNumber() { return value; }

    public static InviteStatus valueOf(int value) {
      switch (value) {
        case 0: return PB_INVITE_INVITED;
        case 1: return PB_INVITE_ACCEPTED;
        case 2: return PB_INVITE_REFUSED;
        case 3: return PB_INVITE_OK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InviteStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<InviteStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InviteStatus>() {
            public InviteStatus findValueByNumber(int number) {
              return InviteStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.SglMsg.getDescriptor().getEnumTypes().get(3);
    }

    private static final InviteStatus[] VALUES = values();

    public static InviteStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private InviteStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SglMsg_pb.InviteStatus)
  }

  /**
   * Protobuf enum {@code SglMsg_pb.ApplyStatus}
   */
  public enum ApplyStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PB_APPLY_APPLIED = 0;</code>
     */
    PB_APPLY_APPLIED(0, 0),
    /**
     * <code>PB_APPLY_ACCEPTED = 1;</code>
     */
    PB_APPLY_ACCEPTED(1, 1),
    /**
     * <code>PB_APPLY_REFUSED = 2;</code>
     */
    PB_APPLY_REFUSED(2, 2),
    /**
     * <code>PB_APPLY_OK = 3;</code>
     */
    PB_APPLY_OK(3, 3),
    ;

    /**
     * <code>PB_APPLY_APPLIED = 0;</code>
     */
    public static final int PB_APPLY_APPLIED_VALUE = 0;
    /**
     * <code>PB_APPLY_ACCEPTED = 1;</code>
     */
    public static final int PB_APPLY_ACCEPTED_VALUE = 1;
    /**
     * <code>PB_APPLY_REFUSED = 2;</code>
     */
    public static final int PB_APPLY_REFUSED_VALUE = 2;
    /**
     * <code>PB_APPLY_OK = 3;</code>
     */
    public static final int PB_APPLY_OK_VALUE = 3;


    public final int getNumber() { return value; }

    public static ApplyStatus valueOf(int value) {
      switch (value) {
        case 0: return PB_APPLY_APPLIED;
        case 1: return PB_APPLY_ACCEPTED;
        case 2: return PB_APPLY_REFUSED;
        case 3: return PB_APPLY_OK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ApplyStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ApplyStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ApplyStatus>() {
            public ApplyStatus findValueByNumber(int number) {
              return ApplyStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.SglMsg.getDescriptor().getEnumTypes().get(4);
    }

    private static final ApplyStatus[] VALUES = values();

    public static ApplyStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ApplyStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SglMsg_pb.ApplyStatus)
  }

  /**
   * Protobuf enum {@code SglMsg_pb.SosStatus}
   */
  public enum SosStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PB_SOS_ISSUED = 0;</code>
     */
    PB_SOS_ISSUED(0, 0),
    /**
     * <code>PB_SOS_RESCUED = 1;</code>
     */
    PB_SOS_RESCUED(1, 1),
    /**
     * <code>PB_SOS_INVALID = 2;</code>
     */
    PB_SOS_INVALID(2, 2),
    /**
     * <code>PB_SOS_OK = 3;</code>
     */
    PB_SOS_OK(3, 3),
    ;

    /**
     * <code>PB_SOS_ISSUED = 0;</code>
     */
    public static final int PB_SOS_ISSUED_VALUE = 0;
    /**
     * <code>PB_SOS_RESCUED = 1;</code>
     */
    public static final int PB_SOS_RESCUED_VALUE = 1;
    /**
     * <code>PB_SOS_INVALID = 2;</code>
     */
    public static final int PB_SOS_INVALID_VALUE = 2;
    /**
     * <code>PB_SOS_OK = 3;</code>
     */
    public static final int PB_SOS_OK_VALUE = 3;


    public final int getNumber() { return value; }

    public static SosStatus valueOf(int value) {
      switch (value) {
        case 0: return PB_SOS_ISSUED;
        case 1: return PB_SOS_RESCUED;
        case 2: return PB_SOS_INVALID;
        case 3: return PB_SOS_OK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SosStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SosStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SosStatus>() {
            public SosStatus findValueByNumber(int number) {
              return SosStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.SglMsg.getDescriptor().getEnumTypes().get(5);
    }

    private static final SosStatus[] VALUES = values();

    public static SosStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SosStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SglMsg_pb.SosStatus)
  }

  public interface SglReqMsgOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<SglReqMsg> {

    // optional .SglMsgType_pb.ProtoMsgType type = 1;
    /**
     * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
     */
    com.leocool.sgland.protocol.SglMsgType.ProtoMsgType getType();

    // optional int64 dt = 2;
    /**
     * <code>optional int64 dt = 2;</code>
     */
    boolean hasDt();
    /**
     * <code>optional int64 dt = 2;</code>
     */
    long getDt();

    // optional int64 user_id = 3;
    /**
     * <code>optional int64 user_id = 3;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int64 user_id = 3;</code>
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code SglMsg_pb.SglReqMsg}
   */
  public static final class SglReqMsg extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        SglReqMsg> implements SglReqMsgOrBuilder {
    // Use SglReqMsg.newBuilder() to construct.
    private SglReqMsg(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.leocool.sgland.protocol.SglMsg.SglReqMsg, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SglReqMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SglReqMsg defaultInstance;
    public static SglReqMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SglReqMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SglReqMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.leocool.sgland.protocol.SglMsgType.ProtoMsgType value = com.leocool.sgland.protocol.SglMsgType.ProtoMsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dt_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.SglMsg.internal_static_SglMsg_pb_SglReqMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leocool.sgland.protocol.SglMsg.internal_static_SglMsg_pb_SglReqMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leocool.sgland.protocol.SglMsg.SglReqMsg.class, com.leocool.sgland.protocol.SglMsg.SglReqMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SglReqMsg> PARSER =
        new com.google.protobuf.AbstractParser<SglReqMsg>() {
      public SglReqMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SglReqMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SglReqMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .SglMsgType_pb.ProtoMsgType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.leocool.sgland.protocol.SglMsgType.ProtoMsgType type_;
    /**
     * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
     */
    public com.leocool.sgland.protocol.SglMsgType.ProtoMsgType getType() {
      return type_;
    }

    // optional int64 dt = 2;
    public static final int DT_FIELD_NUMBER = 2;
    private long dt_;
    /**
     * <code>optional int64 dt = 2;</code>
     */
    public boolean hasDt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 dt = 2;</code>
     */
    public long getDt() {
      return dt_;
    }

    // optional int64 user_id = 3;
    public static final int USER_ID_FIELD_NUMBER = 3;
    private long userId_;
    /**
     * <code>optional int64 user_id = 3;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 user_id = 3;</code>
     */
    public long getUserId() {
      return userId_;
    }

    private void initFields() {
      type_ = com.leocool.sgland.protocol.SglMsgType.ProtoMsgType.PB_TYPE_CHALLENGE;
      dt_ = 0L;
      userId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.leocool.sgland.protocol.SglMsg.SglReqMsg>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, dt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, userId_);
      }
      extensionWriter.writeUntil(10101, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, dt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, userId_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.leocool.sgland.protocol.SglMsg.SglReqMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglReqMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglReqMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglReqMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglReqMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglReqMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglReqMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglReqMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leocool.sgland.protocol.SglMsg.SglReqMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SglMsg_pb.SglReqMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.leocool.sgland.protocol.SglMsg.SglReqMsg, Builder> implements com.leocool.sgland.protocol.SglMsg.SglReqMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leocool.sgland.protocol.SglMsg.internal_static_SglMsg_pb_SglReqMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leocool.sgland.protocol.SglMsg.internal_static_SglMsg_pb_SglReqMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leocool.sgland.protocol.SglMsg.SglReqMsg.class, com.leocool.sgland.protocol.SglMsg.SglReqMsg.Builder.class);
      }

      // Construct using com.leocool.sgland.protocol.SglMsg.SglReqMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.leocool.sgland.protocol.SglMsgType.ProtoMsgType.PB_TYPE_CHALLENGE;
        bitField0_ = (bitField0_ & ~0x00000001);
        dt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leocool.sgland.protocol.SglMsg.internal_static_SglMsg_pb_SglReqMsg_descriptor;
      }

      public com.leocool.sgland.protocol.SglMsg.SglReqMsg getDefaultInstanceForType() {
        return com.leocool.sgland.protocol.SglMsg.SglReqMsg.getDefaultInstance();
      }

      public com.leocool.sgland.protocol.SglMsg.SglReqMsg build() {
        com.leocool.sgland.protocol.SglMsg.SglReqMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leocool.sgland.protocol.SglMsg.SglReqMsg buildPartial() {
        com.leocool.sgland.protocol.SglMsg.SglReqMsg result = new com.leocool.sgland.protocol.SglMsg.SglReqMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dt_ = dt_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leocool.sgland.protocol.SglMsg.SglReqMsg) {
          return mergeFrom((com.leocool.sgland.protocol.SglMsg.SglReqMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leocool.sgland.protocol.SglMsg.SglReqMsg other) {
        if (other == com.leocool.sgland.protocol.SglMsg.SglReqMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDt()) {
          setDt(other.getDt());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leocool.sgland.protocol.SglMsg.SglReqMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leocool.sgland.protocol.SglMsg.SglReqMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .SglMsgType_pb.ProtoMsgType type = 1;
      private com.leocool.sgland.protocol.SglMsgType.ProtoMsgType type_ = com.leocool.sgland.protocol.SglMsgType.ProtoMsgType.PB_TYPE_CHALLENGE;
      /**
       * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public com.leocool.sgland.protocol.SglMsgType.ProtoMsgType getType() {
        return type_;
      }
      /**
       * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public Builder setType(com.leocool.sgland.protocol.SglMsgType.ProtoMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.leocool.sgland.protocol.SglMsgType.ProtoMsgType.PB_TYPE_CHALLENGE;
        onChanged();
        return this;
      }

      // optional int64 dt = 2;
      private long dt_ ;
      /**
       * <code>optional int64 dt = 2;</code>
       */
      public boolean hasDt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 dt = 2;</code>
       */
      public long getDt() {
        return dt_;
      }
      /**
       * <code>optional int64 dt = 2;</code>
       */
      public Builder setDt(long value) {
        bitField0_ |= 0x00000002;
        dt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 dt = 2;</code>
       */
      public Builder clearDt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dt_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 user_id = 3;
      private long userId_ ;
      /**
       * <code>optional int64 user_id = 3;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 user_id = 3;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 user_id = 3;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 user_id = 3;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SglMsg_pb.SglReqMsg)
    }

    static {
      defaultInstance = new SglReqMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SglMsg_pb.SglReqMsg)
  }

  public interface SglRespMsgOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<SglRespMsg> {

    // optional .SglMsgType_pb.ProtoMsgType type = 1;
    /**
     * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
     */
    com.leocool.sgland.protocol.SglMsgType.ProtoMsgType getType();

    // optional .SglMsg_pb.ProtoMsgStatus status = 2;
    /**
     * <code>optional .SglMsg_pb.ProtoMsgStatus status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .SglMsg_pb.ProtoMsgStatus status = 2;</code>
     */
    com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus getStatus();

    // optional string error = 3;
    /**
     * <code>optional string error = 3;</code>
     */
    boolean hasError();
    /**
     * <code>optional string error = 3;</code>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();

    // optional int64 dt = 4;
    /**
     * <code>optional int64 dt = 4;</code>
     */
    boolean hasDt();
    /**
     * <code>optional int64 dt = 4;</code>
     */
    long getDt();
  }
  /**
   * Protobuf type {@code SglMsg_pb.SglRespMsg}
   */
  public static final class SglRespMsg extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        SglRespMsg> implements SglRespMsgOrBuilder {
    // Use SglRespMsg.newBuilder() to construct.
    private SglRespMsg(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.leocool.sgland.protocol.SglMsg.SglRespMsg, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SglRespMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SglRespMsg defaultInstance;
    public static SglRespMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SglRespMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SglRespMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.leocool.sgland.protocol.SglMsgType.ProtoMsgType value = com.leocool.sgland.protocol.SglMsgType.ProtoMsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus value = com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              error_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              dt_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leocool.sgland.protocol.SglMsg.internal_static_SglMsg_pb_SglRespMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leocool.sgland.protocol.SglMsg.internal_static_SglMsg_pb_SglRespMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leocool.sgland.protocol.SglMsg.SglRespMsg.class, com.leocool.sgland.protocol.SglMsg.SglRespMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SglRespMsg> PARSER =
        new com.google.protobuf.AbstractParser<SglRespMsg>() {
      public SglRespMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SglRespMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SglRespMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .SglMsgType_pb.ProtoMsgType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.leocool.sgland.protocol.SglMsgType.ProtoMsgType type_;
    /**
     * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
     */
    public com.leocool.sgland.protocol.SglMsgType.ProtoMsgType getType() {
      return type_;
    }

    // optional .SglMsg_pb.ProtoMsgStatus status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus status_;
    /**
     * <code>optional .SglMsg_pb.ProtoMsgStatus status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .SglMsg_pb.ProtoMsgStatus status = 2;</code>
     */
    public com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus getStatus() {
      return status_;
    }

    // optional string error = 3;
    public static final int ERROR_FIELD_NUMBER = 3;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 3;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 dt = 4;
    public static final int DT_FIELD_NUMBER = 4;
    private long dt_;
    /**
     * <code>optional int64 dt = 4;</code>
     */
    public boolean hasDt() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 dt = 4;</code>
     */
    public long getDt() {
      return dt_;
    }

    private void initFields() {
      type_ = com.leocool.sgland.protocol.SglMsgType.ProtoMsgType.PB_TYPE_CHALLENGE;
      status_ = com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus.PB_STATUS_OK;
      error_ = "";
      dt_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.leocool.sgland.protocol.SglMsg.SglRespMsg>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, dt_);
      }
      extensionWriter.writeUntil(10101, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, dt_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.leocool.sgland.protocol.SglMsg.SglRespMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglRespMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglRespMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglRespMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglRespMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglRespMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglRespMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglRespMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leocool.sgland.protocol.SglMsg.SglRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leocool.sgland.protocol.SglMsg.SglRespMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SglMsg_pb.SglRespMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.leocool.sgland.protocol.SglMsg.SglRespMsg, Builder> implements com.leocool.sgland.protocol.SglMsg.SglRespMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leocool.sgland.protocol.SglMsg.internal_static_SglMsg_pb_SglRespMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leocool.sgland.protocol.SglMsg.internal_static_SglMsg_pb_SglRespMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leocool.sgland.protocol.SglMsg.SglRespMsg.class, com.leocool.sgland.protocol.SglMsg.SglRespMsg.Builder.class);
      }

      // Construct using com.leocool.sgland.protocol.SglMsg.SglRespMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.leocool.sgland.protocol.SglMsgType.ProtoMsgType.PB_TYPE_CHALLENGE;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus.PB_STATUS_OK;
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leocool.sgland.protocol.SglMsg.internal_static_SglMsg_pb_SglRespMsg_descriptor;
      }

      public com.leocool.sgland.protocol.SglMsg.SglRespMsg getDefaultInstanceForType() {
        return com.leocool.sgland.protocol.SglMsg.SglRespMsg.getDefaultInstance();
      }

      public com.leocool.sgland.protocol.SglMsg.SglRespMsg build() {
        com.leocool.sgland.protocol.SglMsg.SglRespMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leocool.sgland.protocol.SglMsg.SglRespMsg buildPartial() {
        com.leocool.sgland.protocol.SglMsg.SglRespMsg result = new com.leocool.sgland.protocol.SglMsg.SglRespMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dt_ = dt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leocool.sgland.protocol.SglMsg.SglRespMsg) {
          return mergeFrom((com.leocool.sgland.protocol.SglMsg.SglRespMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leocool.sgland.protocol.SglMsg.SglRespMsg other) {
        if (other == com.leocool.sgland.protocol.SglMsg.SglRespMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000004;
          error_ = other.error_;
          onChanged();
        }
        if (other.hasDt()) {
          setDt(other.getDt());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leocool.sgland.protocol.SglMsg.SglRespMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leocool.sgland.protocol.SglMsg.SglRespMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .SglMsgType_pb.ProtoMsgType type = 1;
      private com.leocool.sgland.protocol.SglMsgType.ProtoMsgType type_ = com.leocool.sgland.protocol.SglMsgType.ProtoMsgType.PB_TYPE_CHALLENGE;
      /**
       * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public com.leocool.sgland.protocol.SglMsgType.ProtoMsgType getType() {
        return type_;
      }
      /**
       * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public Builder setType(com.leocool.sgland.protocol.SglMsgType.ProtoMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SglMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.leocool.sgland.protocol.SglMsgType.ProtoMsgType.PB_TYPE_CHALLENGE;
        onChanged();
        return this;
      }

      // optional .SglMsg_pb.ProtoMsgStatus status = 2;
      private com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus status_ = com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus.PB_STATUS_OK;
      /**
       * <code>optional .SglMsg_pb.ProtoMsgStatus status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .SglMsg_pb.ProtoMsgStatus status = 2;</code>
       */
      public com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus getStatus() {
        return status_;
      }
      /**
       * <code>optional .SglMsg_pb.ProtoMsgStatus status = 2;</code>
       */
      public Builder setStatus(com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SglMsg_pb.ProtoMsgStatus status = 2;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.leocool.sgland.protocol.SglMsg.ProtoMsgStatus.PB_STATUS_OK;
        onChanged();
        return this;
      }

      // optional string error = 3;
      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 3;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000004);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }

      // optional int64 dt = 4;
      private long dt_ ;
      /**
       * <code>optional int64 dt = 4;</code>
       */
      public boolean hasDt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 dt = 4;</code>
       */
      public long getDt() {
        return dt_;
      }
      /**
       * <code>optional int64 dt = 4;</code>
       */
      public Builder setDt(long value) {
        bitField0_ |= 0x00000008;
        dt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 dt = 4;</code>
       */
      public Builder clearDt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dt_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SglMsg_pb.SglRespMsg)
    }

    static {
      defaultInstance = new SglRespMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SglMsg_pb.SglRespMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SglMsg_pb_SglReqMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SglMsg_pb_SglReqMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SglMsg_pb_SglRespMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SglMsg_pb_SglRespMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SglMsg_pb.proto\022\tSglMsg_pb\032\023SglMsgType" +
      "_pb.proto\"Z\n\tSglReqMsg\022)\n\004type\030\001 \001(\0162\033.S" +
      "glMsgType_pb.ProtoMsgType\022\n\n\002dt\030\002 \001(\003\022\017\n" +
      "\007user_id\030\003 \001(\003*\005\010d\020\365N\"\204\001\n\nSglRespMsg\022)\n\004" +
      "type\030\001 \001(\0162\033.SglMsgType_pb.ProtoMsgType\022" +
      ")\n\006status\030\002 \001(\0162\031.SglMsg_pb.ProtoMsgStat" +
      "us\022\r\n\005error\030\003 \001(\t\022\n\n\002dt\030\004 \001(\003*\005\010d\020\365N*\266\023\n" +
      "\016ProtoMsgStatus\022\020\n\014PB_STATUS_OK\020\000\022!\n\035PB_" +
      "STATUS_AUTHENTICATION_FAIL\020\001\022\031\n\025PB_STATU" +
      "S_INVALID_ARG\020\002\022\030\n\024PB_STATUS_LOGIN_FAIL\020",
      "\003\022\032\n\026PB_STATUS_SERVER_ERROR\020\004\022\030\n\024PB_STAT" +
      "US_DATA_ERROR\020\005\022 \n\034PB_STATUS_OPPONENT_NO" +
      "T_FOUND\020\006\022\031\n\025PB_STATUS_OUT_OF_SYNC\020\007\022\035\n\031" +
      "PB_STATUS_LOGIN_ELSEWHERE\020\010\022\032\n\026PB_STATUS" +
      "_USER_OFFLINE\020\t\022 \n\034PB_STATUS_SERVER_MAIN" +
      "TENANCE\020\n\022\037\n\033PB_STATUS_USER_UNDER_ATTACK" +
      "\020\013\022\031\n\025PB_STATUS_USER_ONLINE\020\014\022\031\n\025PB_STAT" +
      "US_USER_SHILED\020\r\022\032\n\026PB_STATUS_ILLEGAL_NA" +
      "ME\020\016\022\035\n\031PB_STATUS_FRIEND_EXCEEDED\020\017\022\031\n\025P" +
      "B_STATUS_NAME_EXISTS\020\020\022\035\n\031PB_STATUS_INVA",
      "LID_VERSION\020\021\022\034\n\030PB_STATUS_BATTLE_RECOVE" +
      "R\020\022\022\037\n\033PB_STATUS_RACE_NOT_PREPARED\020\023\022%\n!" +
      "PB_STATUS_BATTLE_JOIN_NOT_ALLOWED\020\024\022\031\n\025P" +
      "B_STATUS_BATTLE_WAIT\020\025\022\032\n\026PB_STATUS_CITY" +
      "_FOCUSED\020\026\022\036\n\032PB_STATUS_ALREADY_IN_UNION" +
      "\020\027\022\032\n\026PB_STATUS_UNION_CLOSED\020\030\022\034\n\030PB_STA" +
      "TUS_UNION_EXCEEDED\020\031\022\032\n\026PB_STATUS_NOT_IN" +
      "_UNION\020\032\022\035\n\031PB_STATUS_PRIVILEGE_ERROR\020\033\022" +
      "\027\n\023PB_STATUS_WAR_ENDED\020\034\022\035\n\031PB_STATUS_WA" +
      "R_NOT_STARTED\020\035\022\032\n\026PB_STATUS_GIFT_CLAIME",
      "D\020\036\022\032\n\026PB_STATUS_GIFT_EXPIRED\020\037\022\032\n\026PB_ST" +
      "ATUS_GIFT_INVALID\020 \022\033\n\027PB_STATUS_CAMP_DE" +
      "FEATED\020!\022$\n PB_STATUS_UNION_NOT_ENOUGH_P" +
      "OWER\020\"\022\037\n\033PB_STATUS_UNION_NAME_EXISTS\020#\022" +
      "\036\n\032PB_STATUS_BATTLE_NOT_ENDED\020$\022\034\n\030PB_ST" +
      "ATUS_USER_BAN_LOGIN\020%\022%\n!PB_STATUS_UNION" +
      "_APPLY_NOT_ALLOWED\020&\022\036\n\032PB_STATUS_UNION_" +
      "TAG_EXISTS\020\'\022\033\n\027PB_STATUS_LET_NOT_FOUND\020" +
      "(\022 \n\034PB_STATUS_CO_LEADER_EXCEEDED\020)\022\034\n\030P" +
      "B_STATUS_INVALID_RESCUE\020*\022)\n%PB_STATUS_E",
      "RROR_CONNECT_BATTLE_SERVER\020+\022\036\n\032PB_STATU" +
      "S_INVALID_TUTORIAL\020,\022#\n\037PB_STATUS_BATTLE" +
      "_ALREADY_SHARED\020-\022\037\n\033PB_STATUS_UNION_BOS" +
      "S_LOCKED\020.\022!\n\035PB_STATUS_UNION_BOSS_UNLOC" +
      "KED\020/\022 \n\034PB_STATUS_UNION_BOSS_FOCUSED\0200\022" +
      "\033\n\027PB_STATUS_UNION_JOIN_CD\0201\022\030\n\024PB_STATU" +
      "S_FUND_OWNED\0202\022\034\n\030PB_STATUS_BATTLE_TIMEO" +
      "UT\0203\022 \n\034PB_STATUS_BATTLE_NOT_ALLOWED\0204\022!" +
      "\n\035PB_STATUS_ILLEGAL_INVITE_CODE\0205\022\034\n\030PB_" +
      "STATUS_GIFT_DUPLICATE\0206\022$\n PB_STATUS_MAT",
      "CH_JOIN_NOT_ALLOWED\0207\022%\n!PB_STATUS_MATCH" +
      "_START_NOT_ALLOWED\0208\022 \n\034PB_STATUS_ERROR_" +
      "CREATE_MATCH\0209\022&\n\"PB_STATUS_MASSWAR_JOIN" +
      "_NOT_ALLOWED\020:\022)\n%PB_STATUS_MASSWAR_KICK" +
      "OUT_NOT_ALLOWED\020;\022\'\n#PB_STATUS_MASSWAR_T" +
      "EAM_TROOP_LOCKED\020<\022!\n\035PB_STATUS_MASSWAR_" +
      "NOT_IN_TEAM\020=\022%\n!PB_STATUS_MASSWAR_ALREA" +
      "DY_IN_TEAM\020>\022#\n\037PB_STATUS_MASSWAR_TEAM_N" +
      "OT_FULL\020?\022$\n PB_STATUS_MASSWAR_TROOP_NOT" +
      "_FULL\020@\022\'\n#PB_STATUS_MASSWAR_CANNOT_LEAV",
      "E_TEAM\020A\022 \n\034PB_STATUS_UNOIN_TAG_TOO_LONG" +
      "\020B\022$\n PB_STATUS_DARK_DUEL_CANCEL_MATCH\020C" +
      "\022*\n&PB_STATUS_PLAYER_CAN_NOT_RESEVICE_GI" +
      "FT\020D\022\033\n\027PB_UNION_MEMBER_IN_TEAM\020E\022\034\n\030PB_" +
      "STATUS_ROOM_RECONNECT\020F\022%\n!PB_STATUS_SEA" +
      "SON_JOIN_NOT_ALLOWED\020G\022&\n\"PB_STATUS_SEAS" +
      "ON_START_NOT_ALLOWED\020H\022 \n\034PB_STATUS_REPO" +
      "RT_UPPER_LIMIT\020I\022\035\n\031PB_STATUS_USER_BAN_B" +
      "ATTLE\020J\022$\n PB_STATUS_HAS_LEND_CARD_IN_UN" +
      "ION\020K*D\n\010UserType\022\023\n\017PB_USER_CHAPTER\020\001\022\022",
      "\n\016PB_USER_PLAYER\020\002\022\017\n\013PB_USER_NPC\020\003*v\n\013F" +
      "ocusStatus\022\022\n\016PB_FOCUS_SWEEP\020\001\022\023\n\017PB_FOC" +
      "US_ATTACK\020\002\022\026\n\022PB_FOCUS_CHALLENGE\020\003\022\023\n\017P" +
      "B_FOCUS_RESCUE\020\004\022\021\n\rPB_FOCUS_LOCK\020\005*f\n\014I" +
      "nviteStatus\022\025\n\021PB_INVITE_INVITED\020\000\022\026\n\022PB" +
      "_INVITE_ACCEPTED\020\001\022\025\n\021PB_INVITE_REFUSED\020" +
      "\002\022\020\n\014PB_INVITE_OK\020\003*a\n\013ApplyStatus\022\024\n\020PB" +
      "_APPLY_APPLIED\020\000\022\025\n\021PB_APPLY_ACCEPTED\020\001\022" +
      "\024\n\020PB_APPLY_REFUSED\020\002\022\017\n\013PB_APPLY_OK\020\003*U" +
      "\n\tSosStatus\022\021\n\rPB_SOS_ISSUED\020\000\022\022\n\016PB_SOS",
      "_RESCUED\020\001\022\022\n\016PB_SOS_INVALID\020\002\022\r\n\tPB_SOS" +
      "_OK\020\003B%\n\033com.leocool.sgland.protocolB\006Sg" +
      "lMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SglMsg_pb_SglReqMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SglMsg_pb_SglReqMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SglMsg_pb_SglReqMsg_descriptor,
              new java.lang.String[] { "Type", "Dt", "UserId", });
          internal_static_SglMsg_pb_SglRespMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SglMsg_pb_SglRespMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SglMsg_pb_SglRespMsg_descriptor,
              new java.lang.String[] { "Type", "Status", "Error", "Dt", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.leocool.sgland.protocol.SglMsgType.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
