// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KangMsg_pb.proto

package cn.kang.common.protocol;

public final class KangMsg_pb {
  private KangMsg_pb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code KangMsg_pb.ProtoMsgStatus}
   */
  public enum ProtoMsgStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PB_STATUS_OK = 0;</code>
     */
    PB_STATUS_OK(0, 0),
    ;

    /**
     * <code>PB_STATUS_OK = 0;</code>
     */
    public static final int PB_STATUS_OK_VALUE = 0;


    public final int getNumber() { return value; }

    public static ProtoMsgStatus valueOf(int value) {
      switch (value) {
        case 0: return PB_STATUS_OK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtoMsgStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtoMsgStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtoMsgStatus>() {
            public ProtoMsgStatus findValueByNumber(int number) {
              return ProtoMsgStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.kang.common.protocol.KangMsg_pb.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtoMsgStatus[] VALUES = values();

    public static ProtoMsgStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ProtoMsgStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:KangMsg_pb.ProtoMsgStatus)
  }

  public interface KangReqMsgOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<KangReqMsg> {

    // optional .KangMsgType_pb.ProtoMsgType type = 1;
    /**
     * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
     */
    cn.kang.common.protocol.KangMsgType.ProtoMsgType getType();

    // optional int64 dt = 2;
    /**
     * <code>optional int64 dt = 2;</code>
     */
    boolean hasDt();
    /**
     * <code>optional int64 dt = 2;</code>
     */
    long getDt();

    // optional int64 user_id = 3;
    /**
     * <code>optional int64 user_id = 3;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int64 user_id = 3;</code>
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code KangMsg_pb.KangReqMsg}
   */
  public static final class KangReqMsg extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        KangReqMsg> implements KangReqMsgOrBuilder {
    // Use KangReqMsg.newBuilder() to construct.
    private KangReqMsg(com.google.protobuf.GeneratedMessage.ExtendableBuilder<cn.kang.common.protocol.KangMsg_pb.KangReqMsg, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KangReqMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KangReqMsg defaultInstance;
    public static KangReqMsg getDefaultInstance() {
      return defaultInstance;
    }

    public KangReqMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KangReqMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              cn.kang.common.protocol.KangMsgType.ProtoMsgType value = cn.kang.common.protocol.KangMsgType.ProtoMsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dt_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.kang.common.protocol.KangMsg_pb.internal_static_KangMsg_pb_KangReqMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.kang.common.protocol.KangMsg_pb.internal_static_KangMsg_pb_KangReqMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.kang.common.protocol.KangMsg_pb.KangReqMsg.class, cn.kang.common.protocol.KangMsg_pb.KangReqMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<KangReqMsg> PARSER =
        new com.google.protobuf.AbstractParser<KangReqMsg>() {
      public KangReqMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KangReqMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KangReqMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .KangMsgType_pb.ProtoMsgType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private cn.kang.common.protocol.KangMsgType.ProtoMsgType type_;
    /**
     * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
     */
    public cn.kang.common.protocol.KangMsgType.ProtoMsgType getType() {
      return type_;
    }

    // optional int64 dt = 2;
    public static final int DT_FIELD_NUMBER = 2;
    private long dt_;
    /**
     * <code>optional int64 dt = 2;</code>
     */
    public boolean hasDt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 dt = 2;</code>
     */
    public long getDt() {
      return dt_;
    }

    // optional int64 user_id = 3;
    public static final int USER_ID_FIELD_NUMBER = 3;
    private long userId_;
    /**
     * <code>optional int64 user_id = 3;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 user_id = 3;</code>
     */
    public long getUserId() {
      return userId_;
    }

    private void initFields() {
      type_ = cn.kang.common.protocol.KangMsgType.ProtoMsgType.PB_TYPE_CONNECTED;
      dt_ = 0L;
      userId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<cn.kang.common.protocol.KangMsg_pb.KangReqMsg>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, dt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, userId_);
      }
      extensionWriter.writeUntil(10101, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, dt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, userId_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.kang.common.protocol.KangMsg_pb.KangReqMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangReqMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangReqMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangReqMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangReqMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangReqMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangReqMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangReqMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.kang.common.protocol.KangMsg_pb.KangReqMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KangMsg_pb.KangReqMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          cn.kang.common.protocol.KangMsg_pb.KangReqMsg, Builder> implements cn.kang.common.protocol.KangMsg_pb.KangReqMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.kang.common.protocol.KangMsg_pb.internal_static_KangMsg_pb_KangReqMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.kang.common.protocol.KangMsg_pb.internal_static_KangMsg_pb_KangReqMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.kang.common.protocol.KangMsg_pb.KangReqMsg.class, cn.kang.common.protocol.KangMsg_pb.KangReqMsg.Builder.class);
      }

      // Construct using cn.kang.common.protocol.KangMsg_pb.KangReqMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = cn.kang.common.protocol.KangMsgType.ProtoMsgType.PB_TYPE_CONNECTED;
        bitField0_ = (bitField0_ & ~0x00000001);
        dt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.kang.common.protocol.KangMsg_pb.internal_static_KangMsg_pb_KangReqMsg_descriptor;
      }

      public cn.kang.common.protocol.KangMsg_pb.KangReqMsg getDefaultInstanceForType() {
        return cn.kang.common.protocol.KangMsg_pb.KangReqMsg.getDefaultInstance();
      }

      public cn.kang.common.protocol.KangMsg_pb.KangReqMsg build() {
        cn.kang.common.protocol.KangMsg_pb.KangReqMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.kang.common.protocol.KangMsg_pb.KangReqMsg buildPartial() {
        cn.kang.common.protocol.KangMsg_pb.KangReqMsg result = new cn.kang.common.protocol.KangMsg_pb.KangReqMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dt_ = dt_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.kang.common.protocol.KangMsg_pb.KangReqMsg) {
          return mergeFrom((cn.kang.common.protocol.KangMsg_pb.KangReqMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.kang.common.protocol.KangMsg_pb.KangReqMsg other) {
        if (other == cn.kang.common.protocol.KangMsg_pb.KangReqMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDt()) {
          setDt(other.getDt());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.kang.common.protocol.KangMsg_pb.KangReqMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.kang.common.protocol.KangMsg_pb.KangReqMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .KangMsgType_pb.ProtoMsgType type = 1;
      private cn.kang.common.protocol.KangMsgType.ProtoMsgType type_ = cn.kang.common.protocol.KangMsgType.ProtoMsgType.PB_TYPE_CONNECTED;
      /**
       * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public cn.kang.common.protocol.KangMsgType.ProtoMsgType getType() {
        return type_;
      }
      /**
       * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public Builder setType(cn.kang.common.protocol.KangMsgType.ProtoMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = cn.kang.common.protocol.KangMsgType.ProtoMsgType.PB_TYPE_CONNECTED;
        onChanged();
        return this;
      }

      // optional int64 dt = 2;
      private long dt_ ;
      /**
       * <code>optional int64 dt = 2;</code>
       */
      public boolean hasDt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 dt = 2;</code>
       */
      public long getDt() {
        return dt_;
      }
      /**
       * <code>optional int64 dt = 2;</code>
       */
      public Builder setDt(long value) {
        bitField0_ |= 0x00000002;
        dt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 dt = 2;</code>
       */
      public Builder clearDt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dt_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 user_id = 3;
      private long userId_ ;
      /**
       * <code>optional int64 user_id = 3;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 user_id = 3;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 user_id = 3;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 user_id = 3;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KangMsg_pb.KangReqMsg)
    }

    static {
      defaultInstance = new KangReqMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KangMsg_pb.KangReqMsg)
  }

  public interface KangRespMsgOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<KangRespMsg> {

    // optional .KangMsgType_pb.ProtoMsgType type = 1;
    /**
     * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
     */
    cn.kang.common.protocol.KangMsgType.ProtoMsgType getType();

    // optional .KangMsg_pb.ProtoMsgStatus status = 2;
    /**
     * <code>optional .KangMsg_pb.ProtoMsgStatus status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .KangMsg_pb.ProtoMsgStatus status = 2;</code>
     */
    cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus getStatus();

    // optional string error = 3;
    /**
     * <code>optional string error = 3;</code>
     */
    boolean hasError();
    /**
     * <code>optional string error = 3;</code>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();

    // optional int64 dt = 4;
    /**
     * <code>optional int64 dt = 4;</code>
     */
    boolean hasDt();
    /**
     * <code>optional int64 dt = 4;</code>
     */
    long getDt();
  }
  /**
   * Protobuf type {@code KangMsg_pb.KangRespMsg}
   */
  public static final class KangRespMsg extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        KangRespMsg> implements KangRespMsgOrBuilder {
    // Use KangRespMsg.newBuilder() to construct.
    private KangRespMsg(com.google.protobuf.GeneratedMessage.ExtendableBuilder<cn.kang.common.protocol.KangMsg_pb.KangRespMsg, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KangRespMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KangRespMsg defaultInstance;
    public static KangRespMsg getDefaultInstance() {
      return defaultInstance;
    }

    public KangRespMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KangRespMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              cn.kang.common.protocol.KangMsgType.ProtoMsgType value = cn.kang.common.protocol.KangMsgType.ProtoMsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus value = cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              error_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              dt_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.kang.common.protocol.KangMsg_pb.internal_static_KangMsg_pb_KangRespMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.kang.common.protocol.KangMsg_pb.internal_static_KangMsg_pb_KangRespMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.kang.common.protocol.KangMsg_pb.KangRespMsg.class, cn.kang.common.protocol.KangMsg_pb.KangRespMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<KangRespMsg> PARSER =
        new com.google.protobuf.AbstractParser<KangRespMsg>() {
      public KangRespMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KangRespMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KangRespMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .KangMsgType_pb.ProtoMsgType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private cn.kang.common.protocol.KangMsgType.ProtoMsgType type_;
    /**
     * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
     */
    public cn.kang.common.protocol.KangMsgType.ProtoMsgType getType() {
      return type_;
    }

    // optional .KangMsg_pb.ProtoMsgStatus status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus status_;
    /**
     * <code>optional .KangMsg_pb.ProtoMsgStatus status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .KangMsg_pb.ProtoMsgStatus status = 2;</code>
     */
    public cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus getStatus() {
      return status_;
    }

    // optional string error = 3;
    public static final int ERROR_FIELD_NUMBER = 3;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 3;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 dt = 4;
    public static final int DT_FIELD_NUMBER = 4;
    private long dt_;
    /**
     * <code>optional int64 dt = 4;</code>
     */
    public boolean hasDt() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 dt = 4;</code>
     */
    public long getDt() {
      return dt_;
    }

    private void initFields() {
      type_ = cn.kang.common.protocol.KangMsgType.ProtoMsgType.PB_TYPE_CONNECTED;
      status_ = cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus.PB_STATUS_OK;
      error_ = "";
      dt_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<cn.kang.common.protocol.KangMsg_pb.KangRespMsg>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, dt_);
      }
      extensionWriter.writeUntil(10101, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, dt_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.kang.common.protocol.KangMsg_pb.KangRespMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangRespMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangRespMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangRespMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangRespMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangRespMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangRespMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangRespMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.kang.common.protocol.KangMsg_pb.KangRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.kang.common.protocol.KangMsg_pb.KangRespMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KangMsg_pb.KangRespMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          cn.kang.common.protocol.KangMsg_pb.KangRespMsg, Builder> implements cn.kang.common.protocol.KangMsg_pb.KangRespMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.kang.common.protocol.KangMsg_pb.internal_static_KangMsg_pb_KangRespMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.kang.common.protocol.KangMsg_pb.internal_static_KangMsg_pb_KangRespMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.kang.common.protocol.KangMsg_pb.KangRespMsg.class, cn.kang.common.protocol.KangMsg_pb.KangRespMsg.Builder.class);
      }

      // Construct using cn.kang.common.protocol.KangMsg_pb.KangRespMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = cn.kang.common.protocol.KangMsgType.ProtoMsgType.PB_TYPE_CONNECTED;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus.PB_STATUS_OK;
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.kang.common.protocol.KangMsg_pb.internal_static_KangMsg_pb_KangRespMsg_descriptor;
      }

      public cn.kang.common.protocol.KangMsg_pb.KangRespMsg getDefaultInstanceForType() {
        return cn.kang.common.protocol.KangMsg_pb.KangRespMsg.getDefaultInstance();
      }

      public cn.kang.common.protocol.KangMsg_pb.KangRespMsg build() {
        cn.kang.common.protocol.KangMsg_pb.KangRespMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.kang.common.protocol.KangMsg_pb.KangRespMsg buildPartial() {
        cn.kang.common.protocol.KangMsg_pb.KangRespMsg result = new cn.kang.common.protocol.KangMsg_pb.KangRespMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dt_ = dt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.kang.common.protocol.KangMsg_pb.KangRespMsg) {
          return mergeFrom((cn.kang.common.protocol.KangMsg_pb.KangRespMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.kang.common.protocol.KangMsg_pb.KangRespMsg other) {
        if (other == cn.kang.common.protocol.KangMsg_pb.KangRespMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000004;
          error_ = other.error_;
          onChanged();
        }
        if (other.hasDt()) {
          setDt(other.getDt());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.kang.common.protocol.KangMsg_pb.KangRespMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.kang.common.protocol.KangMsg_pb.KangRespMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .KangMsgType_pb.ProtoMsgType type = 1;
      private cn.kang.common.protocol.KangMsgType.ProtoMsgType type_ = cn.kang.common.protocol.KangMsgType.ProtoMsgType.PB_TYPE_CONNECTED;
      /**
       * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public cn.kang.common.protocol.KangMsgType.ProtoMsgType getType() {
        return type_;
      }
      /**
       * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public Builder setType(cn.kang.common.protocol.KangMsgType.ProtoMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .KangMsgType_pb.ProtoMsgType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = cn.kang.common.protocol.KangMsgType.ProtoMsgType.PB_TYPE_CONNECTED;
        onChanged();
        return this;
      }

      // optional .KangMsg_pb.ProtoMsgStatus status = 2;
      private cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus status_ = cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus.PB_STATUS_OK;
      /**
       * <code>optional .KangMsg_pb.ProtoMsgStatus status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .KangMsg_pb.ProtoMsgStatus status = 2;</code>
       */
      public cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus getStatus() {
        return status_;
      }
      /**
       * <code>optional .KangMsg_pb.ProtoMsgStatus status = 2;</code>
       */
      public Builder setStatus(cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .KangMsg_pb.ProtoMsgStatus status = 2;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = cn.kang.common.protocol.KangMsg_pb.ProtoMsgStatus.PB_STATUS_OK;
        onChanged();
        return this;
      }

      // optional string error = 3;
      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 3;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000004);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }

      // optional int64 dt = 4;
      private long dt_ ;
      /**
       * <code>optional int64 dt = 4;</code>
       */
      public boolean hasDt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 dt = 4;</code>
       */
      public long getDt() {
        return dt_;
      }
      /**
       * <code>optional int64 dt = 4;</code>
       */
      public Builder setDt(long value) {
        bitField0_ |= 0x00000008;
        dt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 dt = 4;</code>
       */
      public Builder clearDt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dt_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KangMsg_pb.KangRespMsg)
    }

    static {
      defaultInstance = new KangRespMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KangMsg_pb.KangRespMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_KangMsg_pb_KangReqMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KangMsg_pb_KangReqMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_KangMsg_pb_KangRespMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KangMsg_pb_KangRespMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020KangMsg_pb.proto\022\nKangMsg_pb\032\024KangMsgT" +
      "ype_pb.proto\"\\\n\nKangReqMsg\022*\n\004type\030\001 \001(\016" +
      "2\034.KangMsgType_pb.ProtoMsgType\022\n\n\002dt\030\002 \001" +
      "(\003\022\017\n\007user_id\030\003 \001(\003*\005\010d\020\365N\"\207\001\n\013KangRespM" +
      "sg\022*\n\004type\030\001 \001(\0162\034.KangMsgType_pb.ProtoM" +
      "sgType\022*\n\006status\030\002 \001(\0162\032.KangMsg_pb.Prot" +
      "oMsgStatus\022\r\n\005error\030\003 \001(\t\022\n\n\002dt\030\004 \001(\003*\005\010" +
      "d\020\365N*\"\n\016ProtoMsgStatus\022\020\n\014PB_STATUS_OK\020\000" +
      "B%\n\027cn.kang.common.protocolB\nKangMsg_pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_KangMsg_pb_KangReqMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_KangMsg_pb_KangReqMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_KangMsg_pb_KangReqMsg_descriptor,
              new java.lang.String[] { "Type", "Dt", "UserId", });
          internal_static_KangMsg_pb_KangRespMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_KangMsg_pb_KangRespMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_KangMsg_pb_KangRespMsg_descriptor,
              new java.lang.String[] { "Type", "Status", "Error", "Dt", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.kang.common.protocol.KangMsgType.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
