// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: awesome.proto

package cn.kang.common.protocol;

public final class PersonMessage {
  private PersonMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(cn.kang.common.protocol.PersonMessage.count);
    registry.add(cn.kang.common.protocol.PersonMessage.likesCnt);
    registry.add(cn.kang.common.protocol.PersonMessage.PersonEx.px);
    registry.add(cn.kang.common.protocol.PersonMessage.PersonEx.py);
  }
  public interface PersonOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Person> {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string email = 3;
    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // repeated string list = 4;
    /**
     * <code>repeated string list = 4;</code>
     */
    java.util.List<java.lang.String>
    getListList();
    /**
     * <code>repeated string list = 4;</code>
     */
    int getListCount();
    /**
     * <code>repeated string list = 4;</code>
     */
    java.lang.String getList(int index);
    /**
     * <code>repeated string list = 4;</code>
     */
    com.google.protobuf.ByteString
        getListBytes(int index);
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Person> implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.ExtendableBuilder<cn.kang.common.protocol.PersonMessage.Person, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                list_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              list_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          list_ = new com.google.protobuf.UnmodifiableLazyStringList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.kang.common.protocol.PersonMessage.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.kang.common.protocol.PersonMessage.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.kang.common.protocol.PersonMessage.Person.class, cn.kang.common.protocol.PersonMessage.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string list = 4;
    public static final int LIST_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList list_;
    /**
     * <code>repeated string list = 4;</code>
     */
    public java.util.List<java.lang.String>
        getListList() {
      return list_;
    }
    /**
     * <code>repeated string list = 4;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated string list = 4;</code>
     */
    public java.lang.String getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated string list = 4;</code>
     */
    public com.google.protobuf.ByteString
        getListBytes(int index) {
      return list_.getByteString(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      email_ = "";
      list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<cn.kang.common.protocol.PersonMessage.Person>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < list_.size(); i++) {
        output.writeBytes(4, list_.getByteString(i));
      }
      extensionWriter.writeUntil(1001, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < list_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(list_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getListList().size();
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.kang.common.protocol.PersonMessage.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.kang.common.protocol.PersonMessage.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.kang.common.protocol.PersonMessage.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.kang.common.protocol.PersonMessage.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.kang.common.protocol.PersonMessage.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.kang.common.protocol.PersonMessage.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.kang.common.protocol.PersonMessage.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          cn.kang.common.protocol.PersonMessage.Person, Builder> implements cn.kang.common.protocol.PersonMessage.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.kang.common.protocol.PersonMessage.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.kang.common.protocol.PersonMessage.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.kang.common.protocol.PersonMessage.Person.class, cn.kang.common.protocol.PersonMessage.Person.Builder.class);
      }

      // Construct using cn.kang.common.protocol.PersonMessage.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.kang.common.protocol.PersonMessage.internal_static_Person_descriptor;
      }

      public cn.kang.common.protocol.PersonMessage.Person getDefaultInstanceForType() {
        return cn.kang.common.protocol.PersonMessage.Person.getDefaultInstance();
      }

      public cn.kang.common.protocol.PersonMessage.Person build() {
        cn.kang.common.protocol.PersonMessage.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.kang.common.protocol.PersonMessage.Person buildPartial() {
        cn.kang.common.protocol.PersonMessage.Person result = new cn.kang.common.protocol.PersonMessage.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          list_ = new com.google.protobuf.UnmodifiableLazyStringList(
              list_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.list_ = list_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.kang.common.protocol.PersonMessage.Person) {
          return mergeFrom((cn.kang.common.protocol.PersonMessage.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.kang.common.protocol.PersonMessage.Person other) {
        if (other == cn.kang.common.protocol.PersonMessage.Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.kang.common.protocol.PersonMessage.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.kang.common.protocol.PersonMessage.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // repeated string list = 4;
      private com.google.protobuf.LazyStringList list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          list_ = new com.google.protobuf.LazyStringArrayList(list_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public java.util.List<java.lang.String>
          getListList() {
        return java.util.Collections.unmodifiableList(list_);
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public int getListCount() {
        return list_.size();
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public java.lang.String getList(int index) {
        return list_.get(index);
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public com.google.protobuf.ByteString
          getListBytes(int index) {
        return list_.getByteString(index);
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public Builder setList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public Builder addList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<java.lang.String> values) {
        ensureListIsMutable();
        super.addAll(values, list_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public Builder clearList() {
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public Builder addListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Person)
  }

  public interface PersonTreeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string id = 1;
    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional string title = 2;
    /**
     * <code>optional string title = 2;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // repeated .PersonTree childs = 3;
    /**
     * <code>repeated .PersonTree childs = 3;</code>
     */
    java.util.List<cn.kang.common.protocol.PersonMessage.PersonTree> 
        getChildsList();
    /**
     * <code>repeated .PersonTree childs = 3;</code>
     */
    cn.kang.common.protocol.PersonMessage.PersonTree getChilds(int index);
    /**
     * <code>repeated .PersonTree childs = 3;</code>
     */
    int getChildsCount();
    /**
     * <code>repeated .PersonTree childs = 3;</code>
     */
    java.util.List<? extends cn.kang.common.protocol.PersonMessage.PersonTreeOrBuilder> 
        getChildsOrBuilderList();
    /**
     * <code>repeated .PersonTree childs = 3;</code>
     */
    cn.kang.common.protocol.PersonMessage.PersonTreeOrBuilder getChildsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PersonTree}
   */
  public static final class PersonTree extends
      com.google.protobuf.GeneratedMessage
      implements PersonTreeOrBuilder {
    // Use PersonTree.newBuilder() to construct.
    private PersonTree(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PersonTree(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PersonTree defaultInstance;
    public static PersonTree getDefaultInstance() {
      return defaultInstance;
    }

    public PersonTree getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PersonTree(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                childs_ = new java.util.ArrayList<cn.kang.common.protocol.PersonMessage.PersonTree>();
                mutable_bitField0_ |= 0x00000004;
              }
              childs_.add(input.readMessage(cn.kang.common.protocol.PersonMessage.PersonTree.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          childs_ = java.util.Collections.unmodifiableList(childs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.kang.common.protocol.PersonMessage.internal_static_PersonTree_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.kang.common.protocol.PersonMessage.internal_static_PersonTree_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.kang.common.protocol.PersonMessage.PersonTree.class, cn.kang.common.protocol.PersonMessage.PersonTree.Builder.class);
    }

    public static com.google.protobuf.Parser<PersonTree> PARSER =
        new com.google.protobuf.AbstractParser<PersonTree>() {
      public PersonTree parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonTree(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PersonTree> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 2;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .PersonTree childs = 3;
    public static final int CHILDS_FIELD_NUMBER = 3;
    private java.util.List<cn.kang.common.protocol.PersonMessage.PersonTree> childs_;
    /**
     * <code>repeated .PersonTree childs = 3;</code>
     */
    public java.util.List<cn.kang.common.protocol.PersonMessage.PersonTree> getChildsList() {
      return childs_;
    }
    /**
     * <code>repeated .PersonTree childs = 3;</code>
     */
    public java.util.List<? extends cn.kang.common.protocol.PersonMessage.PersonTreeOrBuilder> 
        getChildsOrBuilderList() {
      return childs_;
    }
    /**
     * <code>repeated .PersonTree childs = 3;</code>
     */
    public int getChildsCount() {
      return childs_.size();
    }
    /**
     * <code>repeated .PersonTree childs = 3;</code>
     */
    public cn.kang.common.protocol.PersonMessage.PersonTree getChilds(int index) {
      return childs_.get(index);
    }
    /**
     * <code>repeated .PersonTree childs = 3;</code>
     */
    public cn.kang.common.protocol.PersonMessage.PersonTreeOrBuilder getChildsOrBuilder(
        int index) {
      return childs_.get(index);
    }

    private void initFields() {
      id_ = "";
      title_ = "";
      childs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      for (int i = 0; i < childs_.size(); i++) {
        output.writeMessage(3, childs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      for (int i = 0; i < childs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, childs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.kang.common.protocol.PersonMessage.PersonTree parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonTree parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonTree parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonTree parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonTree parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonTree parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonTree parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonTree parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonTree parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonTree parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.kang.common.protocol.PersonMessage.PersonTree prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PersonTree}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.kang.common.protocol.PersonMessage.PersonTreeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.kang.common.protocol.PersonMessage.internal_static_PersonTree_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.kang.common.protocol.PersonMessage.internal_static_PersonTree_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.kang.common.protocol.PersonMessage.PersonTree.class, cn.kang.common.protocol.PersonMessage.PersonTree.Builder.class);
      }

      // Construct using cn.kang.common.protocol.PersonMessage.PersonTree.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChildsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (childsBuilder_ == null) {
          childs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          childsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.kang.common.protocol.PersonMessage.internal_static_PersonTree_descriptor;
      }

      public cn.kang.common.protocol.PersonMessage.PersonTree getDefaultInstanceForType() {
        return cn.kang.common.protocol.PersonMessage.PersonTree.getDefaultInstance();
      }

      public cn.kang.common.protocol.PersonMessage.PersonTree build() {
        cn.kang.common.protocol.PersonMessage.PersonTree result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.kang.common.protocol.PersonMessage.PersonTree buildPartial() {
        cn.kang.common.protocol.PersonMessage.PersonTree result = new cn.kang.common.protocol.PersonMessage.PersonTree(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (childsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            childs_ = java.util.Collections.unmodifiableList(childs_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.childs_ = childs_;
        } else {
          result.childs_ = childsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.kang.common.protocol.PersonMessage.PersonTree) {
          return mergeFrom((cn.kang.common.protocol.PersonMessage.PersonTree)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.kang.common.protocol.PersonMessage.PersonTree other) {
        if (other == cn.kang.common.protocol.PersonMessage.PersonTree.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (childsBuilder_ == null) {
          if (!other.childs_.isEmpty()) {
            if (childs_.isEmpty()) {
              childs_ = other.childs_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureChildsIsMutable();
              childs_.addAll(other.childs_);
            }
            onChanged();
          }
        } else {
          if (!other.childs_.isEmpty()) {
            if (childsBuilder_.isEmpty()) {
              childsBuilder_.dispose();
              childsBuilder_ = null;
              childs_ = other.childs_;
              bitField0_ = (bitField0_ & ~0x00000004);
              childsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChildsFieldBuilder() : null;
            } else {
              childsBuilder_.addAllMessages(other.childs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.kang.common.protocol.PersonMessage.PersonTree parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.kang.common.protocol.PersonMessage.PersonTree) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // optional string title = 2;
      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      // repeated .PersonTree childs = 3;
      private java.util.List<cn.kang.common.protocol.PersonMessage.PersonTree> childs_ =
        java.util.Collections.emptyList();
      private void ensureChildsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          childs_ = new java.util.ArrayList<cn.kang.common.protocol.PersonMessage.PersonTree>(childs_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.kang.common.protocol.PersonMessage.PersonTree, cn.kang.common.protocol.PersonMessage.PersonTree.Builder, cn.kang.common.protocol.PersonMessage.PersonTreeOrBuilder> childsBuilder_;

      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public java.util.List<cn.kang.common.protocol.PersonMessage.PersonTree> getChildsList() {
        if (childsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(childs_);
        } else {
          return childsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public int getChildsCount() {
        if (childsBuilder_ == null) {
          return childs_.size();
        } else {
          return childsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public cn.kang.common.protocol.PersonMessage.PersonTree getChilds(int index) {
        if (childsBuilder_ == null) {
          return childs_.get(index);
        } else {
          return childsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public Builder setChilds(
          int index, cn.kang.common.protocol.PersonMessage.PersonTree value) {
        if (childsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildsIsMutable();
          childs_.set(index, value);
          onChanged();
        } else {
          childsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public Builder setChilds(
          int index, cn.kang.common.protocol.PersonMessage.PersonTree.Builder builderForValue) {
        if (childsBuilder_ == null) {
          ensureChildsIsMutable();
          childs_.set(index, builderForValue.build());
          onChanged();
        } else {
          childsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public Builder addChilds(cn.kang.common.protocol.PersonMessage.PersonTree value) {
        if (childsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildsIsMutable();
          childs_.add(value);
          onChanged();
        } else {
          childsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public Builder addChilds(
          int index, cn.kang.common.protocol.PersonMessage.PersonTree value) {
        if (childsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildsIsMutable();
          childs_.add(index, value);
          onChanged();
        } else {
          childsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public Builder addChilds(
          cn.kang.common.protocol.PersonMessage.PersonTree.Builder builderForValue) {
        if (childsBuilder_ == null) {
          ensureChildsIsMutable();
          childs_.add(builderForValue.build());
          onChanged();
        } else {
          childsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public Builder addChilds(
          int index, cn.kang.common.protocol.PersonMessage.PersonTree.Builder builderForValue) {
        if (childsBuilder_ == null) {
          ensureChildsIsMutable();
          childs_.add(index, builderForValue.build());
          onChanged();
        } else {
          childsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public Builder addAllChilds(
          java.lang.Iterable<? extends cn.kang.common.protocol.PersonMessage.PersonTree> values) {
        if (childsBuilder_ == null) {
          ensureChildsIsMutable();
          super.addAll(values, childs_);
          onChanged();
        } else {
          childsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public Builder clearChilds() {
        if (childsBuilder_ == null) {
          childs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          childsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public Builder removeChilds(int index) {
        if (childsBuilder_ == null) {
          ensureChildsIsMutable();
          childs_.remove(index);
          onChanged();
        } else {
          childsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public cn.kang.common.protocol.PersonMessage.PersonTree.Builder getChildsBuilder(
          int index) {
        return getChildsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public cn.kang.common.protocol.PersonMessage.PersonTreeOrBuilder getChildsOrBuilder(
          int index) {
        if (childsBuilder_ == null) {
          return childs_.get(index);  } else {
          return childsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public java.util.List<? extends cn.kang.common.protocol.PersonMessage.PersonTreeOrBuilder> 
           getChildsOrBuilderList() {
        if (childsBuilder_ != null) {
          return childsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(childs_);
        }
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public cn.kang.common.protocol.PersonMessage.PersonTree.Builder addChildsBuilder() {
        return getChildsFieldBuilder().addBuilder(
            cn.kang.common.protocol.PersonMessage.PersonTree.getDefaultInstance());
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public cn.kang.common.protocol.PersonMessage.PersonTree.Builder addChildsBuilder(
          int index) {
        return getChildsFieldBuilder().addBuilder(
            index, cn.kang.common.protocol.PersonMessage.PersonTree.getDefaultInstance());
      }
      /**
       * <code>repeated .PersonTree childs = 3;</code>
       */
      public java.util.List<cn.kang.common.protocol.PersonMessage.PersonTree.Builder> 
           getChildsBuilderList() {
        return getChildsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.kang.common.protocol.PersonMessage.PersonTree, cn.kang.common.protocol.PersonMessage.PersonTree.Builder, cn.kang.common.protocol.PersonMessage.PersonTreeOrBuilder> 
          getChildsFieldBuilder() {
        if (childsBuilder_ == null) {
          childsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.kang.common.protocol.PersonMessage.PersonTree, cn.kang.common.protocol.PersonMessage.PersonTree.Builder, cn.kang.common.protocol.PersonMessage.PersonTreeOrBuilder>(
                  childs_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          childs_ = null;
        }
        return childsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PersonTree)
    }

    static {
      defaultInstance = new PersonTree(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PersonTree)
  }

  public interface PersonExOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    // optional .Person p = 2;
    /**
     * <code>optional .Person p = 2;</code>
     */
    boolean hasP();
    /**
     * <code>optional .Person p = 2;</code>
     */
    cn.kang.common.protocol.PersonMessage.Person getP();
    /**
     * <code>optional .Person p = 2;</code>
     */
    cn.kang.common.protocol.PersonMessage.PersonOrBuilder getPOrBuilder();
  }
  /**
   * Protobuf type {@code PersonEx}
   */
  public static final class PersonEx extends
      com.google.protobuf.GeneratedMessage
      implements PersonExOrBuilder {
    // Use PersonEx.newBuilder() to construct.
    private PersonEx(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PersonEx(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PersonEx defaultInstance;
    public static PersonEx getDefaultInstance() {
      return defaultInstance;
    }

    public PersonEx getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PersonEx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              cn.kang.common.protocol.PersonMessage.Person.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = p_.toBuilder();
              }
              p_ = input.readMessage(cn.kang.common.protocol.PersonMessage.Person.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(p_);
                p_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.kang.common.protocol.PersonMessage.internal_static_PersonEx_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.kang.common.protocol.PersonMessage.internal_static_PersonEx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.kang.common.protocol.PersonMessage.PersonEx.class, cn.kang.common.protocol.PersonMessage.PersonEx.Builder.class);
    }

    public static com.google.protobuf.Parser<PersonEx> PARSER =
        new com.google.protobuf.AbstractParser<PersonEx>() {
      public PersonEx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonEx(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PersonEx> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional .Person p = 2;
    public static final int P_FIELD_NUMBER = 2;
    private cn.kang.common.protocol.PersonMessage.Person p_;
    /**
     * <code>optional .Person p = 2;</code>
     */
    public boolean hasP() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Person p = 2;</code>
     */
    public cn.kang.common.protocol.PersonMessage.Person getP() {
      return p_;
    }
    /**
     * <code>optional .Person p = 2;</code>
     */
    public cn.kang.common.protocol.PersonMessage.PersonOrBuilder getPOrBuilder() {
      return p_;
    }

    private void initFields() {
      id_ = 0;
      p_ = cn.kang.common.protocol.PersonMessage.Person.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasP()) {
        if (!getP().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, p_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, p_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.kang.common.protocol.PersonMessage.PersonEx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonEx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonEx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonEx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonEx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonEx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonEx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonEx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonEx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.kang.common.protocol.PersonMessage.PersonEx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.kang.common.protocol.PersonMessage.PersonEx prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PersonEx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.kang.common.protocol.PersonMessage.PersonExOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.kang.common.protocol.PersonMessage.internal_static_PersonEx_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.kang.common.protocol.PersonMessage.internal_static_PersonEx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.kang.common.protocol.PersonMessage.PersonEx.class, cn.kang.common.protocol.PersonMessage.PersonEx.Builder.class);
      }

      // Construct using cn.kang.common.protocol.PersonMessage.PersonEx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (pBuilder_ == null) {
          p_ = cn.kang.common.protocol.PersonMessage.Person.getDefaultInstance();
        } else {
          pBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.kang.common.protocol.PersonMessage.internal_static_PersonEx_descriptor;
      }

      public cn.kang.common.protocol.PersonMessage.PersonEx getDefaultInstanceForType() {
        return cn.kang.common.protocol.PersonMessage.PersonEx.getDefaultInstance();
      }

      public cn.kang.common.protocol.PersonMessage.PersonEx build() {
        cn.kang.common.protocol.PersonMessage.PersonEx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.kang.common.protocol.PersonMessage.PersonEx buildPartial() {
        cn.kang.common.protocol.PersonMessage.PersonEx result = new cn.kang.common.protocol.PersonMessage.PersonEx(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (pBuilder_ == null) {
          result.p_ = p_;
        } else {
          result.p_ = pBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.kang.common.protocol.PersonMessage.PersonEx) {
          return mergeFrom((cn.kang.common.protocol.PersonMessage.PersonEx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.kang.common.protocol.PersonMessage.PersonEx other) {
        if (other == cn.kang.common.protocol.PersonMessage.PersonEx.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasP()) {
          mergeP(other.getP());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasP()) {
          if (!getP().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.kang.common.protocol.PersonMessage.PersonEx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.kang.common.protocol.PersonMessage.PersonEx) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional .Person p = 2;
      private cn.kang.common.protocol.PersonMessage.Person p_ = cn.kang.common.protocol.PersonMessage.Person.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.kang.common.protocol.PersonMessage.Person, cn.kang.common.protocol.PersonMessage.Person.Builder, cn.kang.common.protocol.PersonMessage.PersonOrBuilder> pBuilder_;
      /**
       * <code>optional .Person p = 2;</code>
       */
      public boolean hasP() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Person p = 2;</code>
       */
      public cn.kang.common.protocol.PersonMessage.Person getP() {
        if (pBuilder_ == null) {
          return p_;
        } else {
          return pBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Person p = 2;</code>
       */
      public Builder setP(cn.kang.common.protocol.PersonMessage.Person value) {
        if (pBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          p_ = value;
          onChanged();
        } else {
          pBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Person p = 2;</code>
       */
      public Builder setP(
          cn.kang.common.protocol.PersonMessage.Person.Builder builderForValue) {
        if (pBuilder_ == null) {
          p_ = builderForValue.build();
          onChanged();
        } else {
          pBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Person p = 2;</code>
       */
      public Builder mergeP(cn.kang.common.protocol.PersonMessage.Person value) {
        if (pBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              p_ != cn.kang.common.protocol.PersonMessage.Person.getDefaultInstance()) {
            p_ =
              cn.kang.common.protocol.PersonMessage.Person.newBuilder(p_).mergeFrom(value).buildPartial();
          } else {
            p_ = value;
          }
          onChanged();
        } else {
          pBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Person p = 2;</code>
       */
      public Builder clearP() {
        if (pBuilder_ == null) {
          p_ = cn.kang.common.protocol.PersonMessage.Person.getDefaultInstance();
          onChanged();
        } else {
          pBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Person p = 2;</code>
       */
      public cn.kang.common.protocol.PersonMessage.Person.Builder getPBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Person p = 2;</code>
       */
      public cn.kang.common.protocol.PersonMessage.PersonOrBuilder getPOrBuilder() {
        if (pBuilder_ != null) {
          return pBuilder_.getMessageOrBuilder();
        } else {
          return p_;
        }
      }
      /**
       * <code>optional .Person p = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cn.kang.common.protocol.PersonMessage.Person, cn.kang.common.protocol.PersonMessage.Person.Builder, cn.kang.common.protocol.PersonMessage.PersonOrBuilder> 
          getPFieldBuilder() {
        if (pBuilder_ == null) {
          pBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.kang.common.protocol.PersonMessage.Person, cn.kang.common.protocol.PersonMessage.Person.Builder, cn.kang.common.protocol.PersonMessage.PersonOrBuilder>(
                  p_,
                  getParentForChildren(),
                  isClean());
          p_ = null;
        }
        return pBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PersonEx)
    }

    static {
      defaultInstance = new PersonEx(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PersonEx)
    public static final int PX_FIELD_NUMBER = 103;
    /**
     * <code>extend .Person { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        cn.kang.common.protocol.PersonMessage.Person,
        java.lang.Integer> px = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          cn.kang.common.protocol.PersonMessage.PersonEx.getDefaultInstance(),
          0,
          java.lang.Integer.class,
          null);
    public static final int PY_FIELD_NUMBER = 104;
    /**
     * <code>extend .Person { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        cn.kang.common.protocol.PersonMessage.Person,
        java.lang.Integer> py = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          cn.kang.common.protocol.PersonMessage.PersonEx.getDefaultInstance(),
          1,
          java.lang.Integer.class,
          null);
  }

  public static final int COUNT_FIELD_NUMBER = 101;
  /**
   * <code>extend .Person { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      cn.kang.common.protocol.PersonMessage.Person,
      java.lang.Integer> count = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int LIKES_CNT_FIELD_NUMBER = 102;
  /**
   * <code>extend .Person { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      cn.kang.common.protocol.PersonMessage.Person,
      java.lang.Integer> likesCnt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonTree_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PersonTree_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonEx_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PersonEx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rawesome.proto\"F\n\006Person\022\n\n\002id\030\001 \002(\005\022\014\n" +
      "\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\014\n\004list\030\004 \003(\t" +
      "*\005\010d\020\351\007\"D\n\nPersonTree\022\n\n\002id\030\001 \001(\t\022\r\n\005tit" +
      "le\030\002 \001(\t\022\033\n\006childs\030\003 \003(\0132\013.PersonTree\"T\n" +
      "\010PersonEx\022\n\n\002id\030\001 \001(\005\022\022\n\001p\030\002 \001(\0132\007.Perso" +
      "n2\023\n\002px\022\007.Person\030g \001(\0052\023\n\002py\022\007.Person\030h " +
      "\001(\005:\026\n\005count\022\007.Person\030e \001(\005:\032\n\tlikes_cnt" +
      "\022\007.Person\030f \001(\005B(\n\027cn.kang.common.protoc" +
      "olB\rPersonMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_descriptor,
              new java.lang.String[] { "Id", "Name", "Email", "List", });
          internal_static_PersonTree_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PersonTree_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PersonTree_descriptor,
              new java.lang.String[] { "Id", "Title", "Childs", });
          internal_static_PersonEx_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_PersonEx_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PersonEx_descriptor,
              new java.lang.String[] { "Id", "P", });
          count.internalInit(descriptor.getExtensions().get(0));
          likesCnt.internalInit(descriptor.getExtensions().get(1));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
